// ============================================================
// ДЕЛА — БАЗОВЫЙ НАБОР (100 дел)
// Версия 3.0 — Стартовый набор для новичков
// ============================================================

const TASKS_DATA = [

// ============================================================
// УРОВЕНЬ 1 — 50 дел (★ простые, базовые привычки)
// ============================================================
{ id: 1, text: "Выпить стакан воды утром", category: "Здоровье и тело", difficulty: 1, unlockLevel: 1 },
{ id: 2, text: "Сделать 10 отжиманий", category: "Здоровье и тело", difficulty: 1, unlockLevel: 1 },
{ id: 3, text: "Прогуляться 15 минут", category: "Здоровье и тело", difficulty: 1, unlockLevel: 1 },
{ id: 4, text: "Поздороваться с соседом", category: "Отношения и любовь", difficulty: 1, unlockLevel: 1 },
{ id: 5, text: "Убрать на столе", category: "Дом и быт", difficulty: 1, unlockLevel: 1 },
{ id: 6, text: "Помыть посуду", category: "Дом и быт", difficulty: 1, unlockLevel: 1 },
{ id: 7, text: "Заправить кровать", category: "Дом и быт", difficulty: 1, unlockLevel: 1 },
{ id: 8, text: "Почистить зубы 2 минуты", category: "Красота и уход", difficulty: 1, unlockLevel: 1 },
{ id: 9, text: "Улыбнуться незнакомцу", category: "Эмоции и впечатления", difficulty: 1, unlockLevel: 1 },
{ id: 10, text: "Сделать комплимент близкому", category: "Отношения и любовь", difficulty: 1, unlockLevel: 1 },
{ id: 11, text: "Прочитать 5 страниц книги", category: "Навыки и саморазвитие", difficulty: 1, unlockLevel: 1 },
{ id: 12, text: "Написать список дел на день", category: "Навыки и саморазвитие", difficulty: 1, unlockLevel: 1 },
{ id: 13, text: "Проветрить комнату", category: "Дом и быт", difficulty: 1, unlockLevel: 1 },
{ id: 14, text: "Выбросить мусор", category: "Дом и быт", difficulty: 1, unlockLevel: 1 },
{ id: 15, text: "Покормить бездомное животное", category: "Волонтёрство", difficulty: 1, unlockLevel: 1 },
{ id: 16, text: "Позвонить бабушке/дедушке", category: "Отношения и любовь", difficulty: 1, unlockLevel: 1 },
{ id: 17, text: "Сделать 20 приседаний", category: "Здоровье и тело", difficulty: 1, unlockLevel: 1 },
{ id: 18, text: "Выпить чай без сахара", category: "Здоровье и тело", difficulty: 1, unlockLevel: 1 },
{ id: 19, text: "Съесть яблоко", category: "Здоровье и тело", difficulty: 1, unlockLevel: 1 },
{ id: 20, text: "Найти Полярную звезду", category: "Астрономия и космос", difficulty: 1, unlockLevel: 1 },
{ id: 21, text: "Поблагодарить человека", category: "Отношения и любовь", difficulty: 1, unlockLevel: 1 },
{ id: 22, text: "Принять душ", category: "Красота и уход", difficulty: 1, unlockLevel: 1 },
{ id: 23, text: "Надеть чистую одежду", category: "Красота и уход", difficulty: 1, unlockLevel: 1 },
{ id: 24, text: "Найти 1 созвездие", category: "Астрономия и космос", difficulty: 1, unlockLevel: 1 },
{ id: 25, text: "Сделать 5 глубоких вдохов", category: "Здоровье и тело", difficulty: 1, unlockLevel: 1 },
{ id: 26, text: "Улыбнуться своему отражению", category: "Психология", difficulty: 1, unlockLevel: 1 },
{ id: 27, text: "Завязать шнурки красиво", category: "Навыки и саморазвитие", difficulty: 1, unlockLevel: 1 },
{ id: 28, text: "Помочь донести сумку", category: "Волонтёрство", difficulty: 1, unlockLevel: 1 },
{ id: 29, text: "Погладить вещи", category: "Дом и быт", difficulty: 1, unlockLevel: 1 },
{ id: 30, text: "Протереть пыль", category: "Дом и быт", difficulty: 1, unlockLevel: 1 },
{ id: 31, text: "Полить цветы", category: "Садоводство и огород", difficulty: 1, unlockLevel: 1 },
{ id: 32, text: "Съесть морковку", category: "Здоровье и тело", difficulty: 1, unlockLevel: 1 },
{ id: 33, text: "Выключить свет в пустой комнате", category: "Экология", difficulty: 1, unlockLevel: 1 },
{ id: 34, text: "Потратить 5 минут на себя", category: "Эмоции и впечатления", difficulty: 1, unlockLevel: 1 },
{ id: 35, text: "Собрать портфель/сумку", category: "Навыки и саморазвитие", difficulty: 1, unlockLevel: 1 },
{ id: 36, text: "Поставить будильник", category: "Сон и восстановление", difficulty: 1, unlockLevel: 1 },
{ id: 37, text: "Выпить сок", category: "Здоровье и тело", difficulty: 1, unlockLevel: 1 },
{ id: 38, text: "Нарисовать каракулю", category: "Творчество", difficulty: 1, unlockLevel: 1 },
{ id: 39, text: "Спеть песню под душем", category: "Эмоции и впечатления", difficulty: 1, unlockLevel: 1 },
{ id: 40, text: "Записать 1 мысль в дневник", category: "Психология", difficulty: 1, unlockLevel: 1 },
{ id: 41, text: "Пожелать доброго утра", category: "Отношения и любовь", difficulty: 1, unlockLevel: 1 },
{ id: 42, text: "Сделать селфи", category: "Фотография", difficulty: 1, unlockLevel: 1 },
{ id: 43, text: "Посмотреть в окно 2 минуты", category: "Эмоции и впечатления", difficulty: 1, unlockLevel: 1 },
{ id: 44, text: "Спрятать телефон на час", category: "Цифровая гигиена", difficulty: 1, unlockLevel: 1 },
{ id: 45, text: "Найти 1 растение в городе", category: "Гербарий и ботаника", difficulty: 1, unlockLevel: 1 },
{ id: 46, text: "Протереть экран телефона", category: "Цифровая гигиена", difficulty: 1, unlockLevel: 1 },
{ id: 47, text: "Сменить позу при работе", category: "Здоровье и тело", difficulty: 1, unlockLevel: 1 },
{ id: 48, text: "Посмотреть на небо", category: "Астрономия и космос", difficulty: 1, unlockLevel: 1 },
{ id: 49, text: "Сделать зарядку для глаз", category: "Здоровье и тело", difficulty: 1, unlockLevel: 1 },
{ id: 50, text: "Загадать желание", category: "Эмоции и впечатления", difficulty: 1, unlockLevel: 1 },

// ============================================================
// УРОВЕНЬ 2 — 50 дел (★ простые, развитие привычек)
// ============================================================
{ id: 51, text: "Приготовить завтрак самому", category: "Кулинария", difficulty: 1, unlockLevel: 2 },
{ id: 52, text: "Сделать 20 приседаний", category: "Здоровье и тело", difficulty: 1, unlockLevel: 2 },
{ id: 53, text: "Прочитать 10 страниц книги", category: "Навыки и саморазвитие", difficulty: 1, unlockLevel: 2 },
{ id: 54, text: "Убраться в шкафу", category: "Дом и быт", difficulty: 1, unlockLevel: 2 },
{ id: 55, text: "Полить растения", category: "Садоводство и огород", difficulty: 1, unlockLevel: 2 },
{ id: 56, text: "Сделать 5 глубоких вдохов", category: "Здоровье и тело", difficulty: 1, unlockLevel: 2 },
{ id: 57, text: "Помочь родителям", category: "Отношения и любовь", difficulty: 1, unlockLevel: 2 },
{ id: 58, text: "Собрать гербарий из 3 листьев", category: "Гербарий и ботаника", difficulty: 1, unlockLevel: 2 },
{ id: 59, text: "Принять контрастный душ", category: "Красота и уход", difficulty: 1, unlockLevel: 2 },
{ id: 60, text: "Найти свой любимый цвет", category: "Психология", difficulty: 1, unlockLevel: 2 },
{ id: 61, text: "Сделать комплимент коллеге", category: "Отношения и любовь", difficulty: 1, unlockLevel: 2 },
{ id: 62, text: "Выйти на улицу на 10 минут", category: "Здоровье и тело", difficulty: 1, unlockLevel: 2 },
{ id: 63, text: "Погладить себя по голове", category: "Психология", difficulty: 1, unlockLevel: 2 },
{ id: 64, text: "Записать 3 идеи в блокнот", category: "Творчество", difficulty: 1, unlockLevel: 2 },
{ id: 65, text: "Сделать чай с мёдом", category: "Кулинария", difficulty: 1, unlockLevel: 2 },
{ id: 66, text: "Поздравить с днём рождения", category: "Отношения и любовь", difficulty: 1, unlockLevel: 2 },
{ id: 67, text: "Убрать рабочее место", category: "Дом и быт", difficulty: 1, unlockLevel: 2 },
{ id: 68, text: "Сделать покупки по списку", category: "Финансы", difficulty: 1, unlockLevel: 2 },
{ id: 69, text: "Выключить уведомления на час", category: "Цифровая гигиена", difficulty: 1, unlockLevel: 2 },
{ id: 70, text: "Найти на небе Венеру", category: "Астрономия и космос", difficulty: 1, unlockLevel: 2 },
{ id: 71, text: "Приготовить салат", category: "Кулинария", difficulty: 1, unlockLevel: 2 },
{ id: 72, text: "Сделать маску для лица", category: "Красота и уход", difficulty: 1, unlockLevel: 2 },
{ id: 73, text: "Прочитать 1 статью", category: "Навыки и саморазвитие", difficulty: 1, unlockLevel: 2 },
{ id: 74, text: "Собрать рюкзак на завтра", category: "Навыки и саморазвитие", difficulty: 1, unlockLevel: 2 },
{ id: 75, text: "Покормить птиц", category: "Волонтёрство", difficulty: 1, unlockLevel: 2 },
{ id: 76, text: "Сделать массаж стоп", category: "Здоровье и тело", difficulty: 1, unlockLevel: 2 },
{ id: 77, text: "Написать благодарность", category: "Письма", difficulty: 1, unlockLevel: 2 },
{ id: 78, text: "Протереть зеркало", category: "Дом и быт", difficulty: 1, unlockLevel: 2 },
{ id: 79, text: "Сделать 10 выпадов", category: "Здоровье и тело", difficulty: 1, unlockLevel: 2 },
{ id: 80, text: "Выбрать одежду на завтра", category: "Красота и уход", difficulty: 1, unlockLevel: 2 },
{ id: 81, text: "Заварить травяной чай", category: "Кулинария", difficulty: 1, unlockLevel: 2 },
{ id: 82, text: "Улыбнуться 5 раз", category: "Эмоции и впечатления", difficulty: 1, unlockLevel: 2 },
{ id: 83, text: "Найти 1 гриб", category: "Гербарий и ботаника", difficulty: 1, unlockLevel: 2 },
{ id: 84, text: "Сделать доброе дело", category: "Волонтёрство", difficulty: 1, unlockLevel: 2 },
{ id: 85, text: "Послушать природу", category: "Эмоции и впечатления", difficulty: 1, unlockLevel: 2 },
{ id: 86, text: "Полить цветы", category: "Садоводство и огород", difficulty: 1, unlockLevel: 2 },
{ id: 87, text: "Сделать зарядку 5 минут", category: "Здоровье и тело", difficulty: 1, unlockLevel: 2 },
{ id: 88, text: "Выпить кефир", category: "Здоровье и тело", difficulty: 1, unlockLevel: 2 },
{ id: 89, text: "Написать список покупок", category: "Навыки и саморазвитие", difficulty: 1, unlockLevel: 2 },
{ id: 90, text: "Почистить обувь", category: "Дом и быт", difficulty: 1, unlockLevel: 2 },
{ id: 91, text: "Сделать стакан воды", category: "Здоровье и тело", difficulty: 1, unlockLevel: 2 },
{ id: 92, text: "Посмотреть вверх", category: "Астрономия и космос", difficulty: 1, unlockLevel: 2 },
{ id: 93, text: "Помыть фрукты", category: "Кулинария", difficulty: 1, unlockLevel: 2 },
{ id: 94, text: "Сказать 'спасибо' 3 раза", category: "Отношения и любовь", difficulty: 1, unlockLevel: 2 },
{ id: 95, text: "Нарисовать солнце", category: "Творчество", difficulty: 1, unlockLevel: 2 },
{ id: 96, text: "Проветрить подушку", category: "Сон и восстановление", difficulty: 1, unlockLevel: 2 },
{ id: 97, text: "Сделать скраб для рук", category: "Красота и уход", difficulty: 1, unlockLevel: 2 },
{ id: 98, text: "Завязать узел", category: "Навыки и саморазвитие", difficulty: 1, unlockLevel: 2 },
{ id: 99, text: "Посчитать до 100", category: "Психология", difficulty: 1, unlockLevel: 2 },
{ id: 100, text: "Провести 5 минут в тишине", category: "Психология", difficulty: 1, unlockLevel: 2 }
];
