// packages/extreme.js
// ============================================================
// ПАКЕТ "ЭКСТРИМ" — 100 дел для искателей адреналина
// Уровень открытия: 5
// ============================================================

export const tasks = [
    // ============================================================
    // УРОВЕНЬ 5 — НАЧАЛО ЭКСТРИМА
    // ============================================================
    { id: 1201, text: "Прыгнуть с парашютом в тандеме", category: "Экстрим", difficulty: 3, unlockLevel: 5 },
    { id: 1202, text: "Сыграть в покер в казино", category: "Эмоции и впечатления", difficulty: 3, unlockLevel: 5 },
    { id: 1203, text: "Спеть караоке перед незнакомцами", category: "Эмоции и впечатления", difficulty: 3, unlockLevel: 5 },
    { id: 1204, text: "Прожить 24 часа без сна", category: "Эмоции и впечатления", difficulty: 3, unlockLevel: 5 },
    { id: 1205, text: "Сходить на свидание вслепую", category: "Эмоции и впечатления", difficulty: 3, unlockLevel: 5 },
    { id: 1206, text: "Остаться без денег в незнакомом городе", category: "Эмоции и впечатления", difficulty: 3, unlockLevel: 5 },
    { id: 1207, text: "Устроить день немотивированной радости", category: "Эмоции и впечатления", difficulty: 3, unlockLevel: 5 },
    { id: 1208, text: "Посетить концерт любимого музыканта", category: "Эмоции и впечатления", difficulty: 3, unlockLevel: 5 },
    { id: 1209, text: "Переспать под открытым небом в палатке", category: "Эмоции и впечатления", difficulty: 3, unlockLevel: 5 },
    { id: 1210, text: "Участвовать в забеге с препятствиями", category: "Экстрим", difficulty: 3, unlockLevel: 5 },
    { id: 1211, text: "Попробовать уличную еду народов России", category: "Эмоции и впечатления", difficulty: 3, unlockLevel: 5 },
    { id: 1212, text: "Сделать тату или пирсинг", category: "Эмоции и впечатления", difficulty: 3, unlockLevel: 5 },
    { id: 1213, text: "Написать анонимное доброе письмо", category: "Эмоции и впечатления", difficulty: 3, unlockLevel: 5 },
    { id: 1214, text: "Пойти на карнавал в Воронеже", category: "Эмоции и впечатления", difficulty: 3, unlockLevel: 5 },
    { id: 1215, text: "Испытать невесомость в аэродинамической трубе", category: "Экстрим", difficulty: 3, unlockLevel: 5 },
    { id: 1216, text: "Сходить на терапию и поработать над собой", category: "Психология", difficulty: 3, unlockLevel: 5 },
    { id: 1217, text: "Проснуться на рассвете в безлюдном месте", category: "Эмоции и впечатления", difficulty: 3, unlockLevel: 5 },
    { id: 1218, text: "Прожить день по чужому расписанию", category: "Эмоции и впечатления", difficulty: 3, unlockLevel: 5 },
    { id: 1219, text: "Сделать то, что будет смешно вспоминать", category: "Эмоции и впечатления", difficulty: 3, unlockLevel: 5 },
    { id: 1220, text: "Пойти в ресторан в одиночестве", category: "Эмоции и впечатления", difficulty: 3, unlockLevel: 5 },
    { id: 1221, text: "Сделать предложение или признаться в любви первым", category: "Эмоции и впечатления", difficulty: 3, unlockLevel: 5 },
    { id: 1222, text: "Сплавиться по горной реке кат. 3-4", category: "Экстрим", difficulty: 3, unlockLevel: 5 },
    { id: 1223, text: "Прыгнуть с тарзанки", category: "Экстрим", difficulty: 3, unlockLevel: 5 },
    { id: 1224, text: "Покататься на гидроцикле 50+ км/ч", category: "Экстрим", difficulty: 3, unlockLevel: 5 },
    { id: 1225, text: "Заняться вейкбордингом", category: "Экстрим", difficulty: 3, unlockLevel: 5 },
    { id: 1226, text: "Нырнуть с аквалангом на 10+ метров", category: "Экстрим", difficulty: 3, unlockLevel: 5 },
    { id: 1227, text: "Взойти на техническую вершину", category: "Экстрим", difficulty: 3, unlockLevel: 5 },
    { id: 1228, text: "Пройти по подвесному мосту над ущельем", category: "Экстрим", difficulty: 3, unlockLevel: 5 },
    { id: 1229, text: "Спуститься в пещеру вертикально", category: "Экстрим", difficulty: 3, unlockLevel: 5 },
    { id: 1230, text: "Спуститься на лыжах по чёрной трассе", category: "Экстрим", difficulty: 3, unlockLevel: 5 },
    { id: 1231, text: "Нырнуть в прорубь на Крещение", category: "Экстрим", difficulty: 3, unlockLevel: 5 },
    { id: 1232, text: "Прыгнуть с парашютом самостоятельно", category: "Экстрим", difficulty: 3, unlockLevel: 5 },
    { id: 1233, text: "Полететь на дельталёте", category: "Экстрим", difficulty: 3, unlockLevel: 5 },
    { id: 1234, text: "Пройти квест на выживание в лесу", category: "Экстрим", difficulty: 3, unlockLevel: 5 },
    { id: 1235, text: "Пережить грозу в горах", category: "Экстрим", difficulty: 3, unlockLevel: 5 },
    { id: 1236, text: "Покататься на сноубайке", category: "Экстрим", difficulty: 3, unlockLevel: 5 },
    { id: 1237, text: "Участвовать в гонке на снегоходах", category: "Экстрим", difficulty: 3, unlockLevel: 5 },
    { id: 1238, text: "Провести ночь в снежной пещере", category: "Экстрим", difficulty: 3, unlockLevel: 5 },
    { id: 1239, text: "Пробежать трейловый забег 30+ км", category: "Экстрим", difficulty: 3, unlockLevel: 5 },
    { id: 1240, text: "Поплавать с китами или дельфинами", category: "Экстрим", difficulty: 3, unlockLevel: 5 },
    { id: 1241, text: "Переплыть пролив или широкую реку", category: "Экстрим", difficulty: 3, unlockLevel: 5 },
    { id: 1242, text: "Пройти по канатной дороге над ущельем", category: "Экстрим", difficulty: 3, unlockLevel: 5 },
    { id: 1243, text: "Заночевать в пещере", category: "Экстрим", difficulty: 3, unlockLevel: 5 },
    { id: 1244, text: "Пройти курсы самообороны", category: "Самооборона", difficulty: 3, unlockLevel: 5 },
    { id: 1245, text: "Научиться правильно падать", category: "Самооборона", difficulty: 3, unlockLevel: 5 },
    { id: 1246, text: "Освоить приём освобождения от захвата", category: "Самооборона", difficulty: 3, unlockLevel: 5 },
    { id: 1247, text: "Пройти курсы тактической медицины", category: "Самооборона", difficulty: 3, unlockLevel: 5 },
    { id: 1248, text: "Отработать сценарий нападения в подъезде", category: "Самооборона", difficulty: 3, unlockLevel: 5 },
    { id: 1249, text: "Собрать тревожный рюкзак", category: "Самооборона", difficulty: 3, unlockLevel: 5 },
    { id: 1250, text: "Научиться разжигать костёр в любую погоду", category: "Самооборона", difficulty: 3, unlockLevel: 5 },
    
    // ============================================================
    // УРОВЕНЬ 6 — ЭКСТРЕМАЛЬНЫЙ ЭКСТРИМ
    // ============================================================
    { id: 1251, text: "Прыгнуть с парашютом с высоты 4000 м", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1252, text: "Совершить восхождение на Эльбрус", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1253, text: "Сплавиться по горной реке кат. 5", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1254, text: "Нырнуть с аквалангом на 30+ метров", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1255, text: "Пройти триатлон (Ironman)", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1256, text: "Совершить бейс-джамп", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1257, text: "Прокатиться на горных лыжах с вертолёта", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1258, text: "Провести ночь в лесу без снаряжения", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1259, text: "Пересечь пустыню на велосипеде", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1260, text: "Прыгнуть с моста на эластичной верёвке", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1261, text: "Взойти на вершину выше 7000 м", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1262, text: "Совершить кругосветное путешествие", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1263, text: "Проплыть 10 км в открытом море", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1264, text: "Совершить восхождение на 8-тысячник", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1265, text: "Пройти 100 км по пустыне", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1266, text: "Совершить перелёт на параплане 100+ км", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1267, text: "Провести 7 дней в изоляции без еды", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1268, text: "Совершить погружение к затонувшему кораблю", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1269, text: "Пройти марафон в пустыне", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1270, text: "Совершить восхождение на вулкан", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1271, text: "Покататься на сноуборде с самого высокого склона", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1272, text: "Переплыть Байкал", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1273, text: "Совершить кругосветку на яхте", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1274, text: "Прыгнуть с парашютом в невесомости", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1275, text: "Пройти 500 км по тайге", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1276, text: "Совершить восхождение на К2", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1277, text: "Проплыть 50 км в открытом океане", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1278, text: "Пройти марафон по льду Антарктиды", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1279, text: "Совершить восхождение на все 7 вершин", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1280, text: "Провести месяц в полной изоляции в тайге", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1281, text: "Совершить переход через Гренландию", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1282, text: "Прыгнуть с парашютом на Северный полюс", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1283, text: "Пройти 1000 км на байдарке", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1284, text: "Совершить восхождение на Лхоцзе", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1285, text: "Проплыть через Берингов пролив", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1286, text: "Пройти марафон на все континенты", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1287, text: "Совершить переход через Амазонку", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1288, text: "Прыгнуть с парашютом в ночи", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1289, text: "Пройти 100 км по льду Байкала", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1290, text: "Совершить восхождение на Макалу", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1291, text: "Проплыть 100 км по горной реке", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1292, text: "Пройти 500 км по Сахаре", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1293, text: "Совершить кругосветку на велосипеде", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1294, text: "Прыгнуть с парашютом из стратосферы", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1295, text: "Пройти 1000 км по бездорожью", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1296, text: "Совершить восхождение на все 14 восьмитысячников", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1297, text: "Проплыть через Тихий океан", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1298, text: "Пройти 1000 км по пустыне Гоби", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1299, text: "Совершить переход через Памир", category: "Экстрим", difficulty: 4, unlockLevel: 6 },
    { id: 1300, text: "Стать легендой экстрима", category: "Экстрим", difficulty: 4, unlockLevel: 6 }
];

export default tasks;