// packages/cooking.js
// ============================================================
// ПАКЕТ "КУЛИНАРИЯ" — 100 кулинарных приключений
// Уровень открытия: 3
// ============================================================

export const tasks = [
    // ============================================================
    // УРОВЕНЬ 3 — ОСНОВЫ КУЛИНАРИИ
    // ============================================================
    { id: 401, text: "Приготовить завтрак с нуля", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 402, text: "Приготовить суп", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 403, text: "Испечь печенье", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 404, text: "Приготовить салат", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 405, text: "Сварить варенье", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 406, text: "Приготовить омлет", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 407, text: "Испечь хлеб без хлебопечки", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 408, text: "Приготовить ужин для семьи", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 409, text: "Сделать домашний лимонад", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 410, text: "Приготовить кашу", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 411, text: "Засолить огурцы на зиму", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 412, text: "Приготовить блюдо на пару", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 413, text: "Сделать фруктовый салат", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 414, text: "Приготовить домашний квас", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 415, text: "Сделать домашний творог или сыр", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 416, text: "Приготовить блюдо из дикоросов", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 417, text: "Сделать домашнюю пастилу", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 418, text: "Приготовить овощное рагу", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 419, text: "Испечь блины на Масленицу", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 420, text: "Сделать домашний кефир", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 421, text: "Приготовить пельмени с нуля", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 422, text: "Приготовить осетинский пирог", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 423, text: "Сварить уху", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 424, text: "Приготовить медовик", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 425, text: "Замариновать грибы", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 426, text: "Приготовить бешбармак", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 427, text: "Сварить холодец с нуля", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 428, text: "Приготовить вареники с вишней", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 429, text: "Сделать домашнее мороженое", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 430, text: "Приготовить безе или меренговый рулет", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 431, text: "Засолить сало", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 432, text: "Сделать домашний творог", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 433, text: "Приготовить блюдо на костре", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 434, text: "Сделать домашний майонез", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 435, text: "Приготовить буузы или позы", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 436, text: "Испечь шарлотку", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 437, text: "Приготовить жаркое", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 438, text: "Сделать домашний лимонад", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 439, text: "Приготовить овощной суп-пюре", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 440, text: "Испечь кекс", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 441, text: "Приготовить блюдо из рыбы", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 442, text: "Сварить борщ", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 443, text: "Приготовить голубцы", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 444, text: "Испечь пирог с яблоками", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 445, text: "Приготовить курицу в духовке", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 446, text: "Сделать домашнее варенье", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 447, text: "Приготовить драники", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 448, text: "Сварить компот", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 449, text: "Приготовить сырники", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    { id: 450, text: "Испечь пряники", category: "Кулинария", difficulty: 2, unlockLevel: 3 },
    
    // ============================================================
    // УРОВЕНЬ 4 — КУЛИНАРНОЕ МАСТЕРСТВО
    // ============================================================
    { id: 451, text: "Приготовить 10 блюд без рецепта", category: "Кулинария", difficulty: 3, unlockLevel: 4 },
    { id: 452, text: "Освоить 5 видов теста", category: "Кулинария", difficulty: 3, unlockLevel: 4 },
    { id: 453, text: "Приготовить собственный рецепт", category: "Кулинария", difficulty: 3, unlockLevel: 4 },
    { id: 454, text: "Запечь рыбу целиком", category: "Кулинария", difficulty: 3, unlockLevel: 4 },
    { id: 455, text: "Приготовить ужин для 6 человек", category: "Гостеприимство", difficulty: 3, unlockLevel: 4 },
    { id: 456, text: "Накрыть стол для 6 человек с нуля", category: "Гостеприимство", difficulty: 3, unlockLevel: 4 },
    { id: 457, text: "Организовать тематическую вечеринку", category: "Гостеприимство", difficulty: 3, unlockLevel: 4 },
    { id: 458, text: "Принять гостей на ночь", category: "Гостеприимство", difficulty: 3, unlockLevel: 4 },
    { id: 459, text: "Сделать домашний квиз", category: "Гостеприимство", difficulty: 3, unlockLevel: 4 },
    { id: 460, text: "Провести киновечер с проектором", category: "Гостеприимство", difficulty: 3, unlockLevel: 4 },
    { id: 461, text: "Устроить настолки на 8+ человек", category: "Гостеприимство", difficulty: 3, unlockLevel: 4 },
    { id: 462, text: "Организовать квартирник", category: "Гостеприимство", difficulty: 3, unlockLevel: 4 },
    { id: 463, text: "Провести дегустацию", category: "Гостеприимство", difficulty: 3, unlockLevel: 4 },
    { id: 464, text: "Устроить кулинарный баттл с друзьями", category: "Гостеприимство", difficulty: 3, unlockLevel: 4 },
    { id: 465, text: "Сделать вечеринку-сюрприз для именинника", category: "Гостеприимство", difficulty: 3, unlockLevel: 4 },
    { id: 466, text: "Принять гостей на даче с шашлыками", category: "Гостеприимство", difficulty: 3, unlockLevel: 4 },
    { id: 467, text: "Устроить чаепитие с самоваром", category: "Гостеприимство", difficulty: 3, unlockLevel: 4 },
    { id: 468, text: "Приготовить блюдо из своей рыбы", category: "Кулинария", difficulty: 3, unlockLevel: 4 },
    { id: 469, text: "Сварить варенье из лесных ягод", category: "Кулинария", difficulty: 3, unlockLevel: 4 },
    { id: 470, text: "Приготовить строганину", category: "Кулинария", difficulty: 3, unlockLevel: 4 },
    
    // ============================================================
    // УРОВЕНЬ 5 — ПРОФЕССИОНАЛЬНАЯ КУЛИНАРИЯ
    // ============================================================
    { id: 471, text: "Создать свой первый кулинарный шедевр", category: "Кулинария", difficulty: 4, unlockLevel: 5 },
    { id: 472, text: "Приготовить блюдо по рецепту известного шеф-повара", category: "Кулинария", difficulty: 4, unlockLevel: 5 },
    { id: 473, text: "Организовать кулинарный мастер-класс", category: "Гостеприимство", difficulty: 4, unlockLevel: 5 },
    { id: 474, text: "Приготовить сложное блюдо из 5+ ингредиентов", category: "Кулинария", difficulty: 4, unlockLevel: 5 },
    { id: 475, text: "Создать собственный кулинарный блог", category: "Творчество", difficulty: 4, unlockLevel: 5 },
    { id: 476, text: "Приготовить торт с нуля", category: "Кулинария", difficulty: 4, unlockLevel: 5 },
    { id: 477, text: "Освоить молекулярную кухню", category: "Кулинария", difficulty: 4, unlockLevel: 5 },
    { id: 478, text: "Приготовить блюдо в стиле высокой кухни", category: "Кулинария", difficulty: 4, unlockLevel: 5 },
    { id: 479, text: "Организовать гастрономический тур", category: "Гостеприимство", difficulty: 4, unlockLevel: 5 },
    { id: 480, text: "Создать свою кулинарную книгу", category: "Творчество", difficulty: 4, unlockLevel: 5 },
    { id: 481, text: "Приготовить блюдо из 10+ ингредиентов", category: "Кулинария", difficulty: 4, unlockLevel: 5 },
    { id: 482, text: "Освоить технику су-вид", category: "Кулинария", difficulty: 4, unlockLevel: 5 },
    { id: 483, text: "Приготовить карвинг из овощей", category: "Кулинария", difficulty: 4, unlockLevel: 5 },
    { id: 484, text: "Создать свой фирменный соус", category: "Кулинария", difficulty: 4, unlockLevel: 5 },
    { id: 485, text: "Приготовить десерт в ресторанном стиле", category: "Кулинария", difficulty: 4, unlockLevel: 5 },
    { id: 486, text: "Освоить азиатскую кухню", category: "Кулинария", difficulty: 4, unlockLevel: 5 },
    { id: 487, text: "Провести кулинарный вечер для друзей", category: "Гостеприимство", difficulty: 4, unlockLevel: 5 },
    { id: 488, text: "Приготовить блюдо по семейному рецепту", category: "Кулинария", difficulty: 4, unlockLevel: 5 },
    { id: 489, text: "Сделать домашний мармелад", category: "Кулинария", difficulty: 4, unlockLevel: 5 },
    { id: 490, text: "Приготовить блюдо из 7+ овощей", category: "Кулинария", difficulty: 4, unlockLevel: 5 },
    { id: 491, text: "Освоить грузинскую кухню", category: "Кулинария", difficulty: 4, unlockLevel: 5 },
    { id: 492, text: "Приготовить блюдо на открытом огне", category: "Кулинария", difficulty: 4, unlockLevel: 5 },
    { id: 493, text: "Сделать домашний сыр", category: "Кулинария", difficulty: 4, unlockLevel: 5 },
    { id: 494, text: "Приготовить рыбное филе в 5 вариантах", category: "Кулинария", difficulty: 4, unlockLevel: 5 },
    { id: 495, text: "Освоить итальянскую пасту", category: "Кулинария", difficulty: 4, unlockLevel: 5 },
    { id: 496, text: "Приготовить фуа-гра в домашних условиях", category: "Кулинария", difficulty: 4, unlockLevel: 5 },
    { id: 497, text: "Создать авторское меню на неделю", category: "Кулинария", difficulty: 4, unlockLevel: 5 },
    { id: 498, text: "Приготовить блюдо из морепродуктов", category: "Кулинария", difficulty: 4, unlockLevel: 5 },
    { id: 499, text: "Освоить французскую выпечку", category: "Кулинария", difficulty: 4, unlockLevel: 5 },
    { id: 500, text: "Создать блюдо-победитель на семейном ужине", category: "Кулинария", difficulty: 4, unlockLevel: 5 }
];

export default tasks;