// packages/creative.js
// ============================================================
// ПАКЕТ "ТВОРЧЕСТВО" — 100 дел для вдохновения
// Уровень открытия: 4
// ============================================================

export const tasks = [
    // ============================================================
    // УРОВЕНЬ 4 — НАЧАЛО ТВОРЧЕСТВА
    // ============================================================
    { id: 601, text: "Написать рассказ 20 страниц", category: "Творчество", difficulty: 3, unlockLevel: 4 },
    { id: 602, text: "Снять короткометражку на телефон", category: "Творчество", difficulty: 3, unlockLevel: 4 },
    { id: 603, text: "Нарисовать картину для незнакомца", category: "Творчество", difficulty: 3, unlockLevel: 4 },
    { id: 604, text: "Слепить из глины и обжечь", category: "Творчество", difficulty: 3, unlockLevel: 4 },
    { id: 605, text: "Сочинить стих", category: "Творчество", difficulty: 3, unlockLevel: 4 },
    { id: 606, text: "Записать песню", category: "Творчество", difficulty: 3, unlockLevel: 4 },
    { id: 607, text: "Сделать печатный фотоальбом", category: "Творчество", difficulty: 3, unlockLevel: 4 },
    { id: 608, text: "Создать что-то из дерева", category: "Творчество", difficulty: 3, unlockLevel: 4 },
    { id: 609, text: "Выйти на сцену (стендап, стихи)", category: "Творчество", difficulty: 3, unlockLevel: 4 },
    { id: 610, text: "Организовать квартирник", category: "Творчество", difficulty: 3, unlockLevel: 4 },
    { id: 611, text: "Написать письмо в будущее", category: "Творчество", difficulty: 3, unlockLevel: 4 },
    { id: 612, text: "Сделать подарок своими руками", category: "Творчество", difficulty: 3, unlockLevel: 4 },
    { id: 613, text: "Придумать новый рецепт", category: "Творчество", difficulty: 3, unlockLevel: 4 },
    { id: 614, text: "Украсить дом самодельной вещью", category: "Творчество", difficulty: 3, unlockLevel: 4 },
    { id: 615, text: "Вышить что-то", category: "Творчество", difficulty: 3, unlockLevel: 4 },
    { id: 616, text: "Написать отзыв на книгу или фильм", category: "Творчество", difficulty: 3, unlockLevel: 4 },
    { id: 617, text: "Сделать коллаж желаний на стене", category: "Творчество", difficulty: 3, unlockLevel: 4 },
    { id: 618, text: "Создать семейный архив", category: "Творчество", difficulty: 3, unlockLevel: 4 },
    { id: 619, text: "Сделать альбом с фотографиями жизни", category: "Творчество", difficulty: 3, unlockLevel: 4 },
    { id: 620, text: "Написать автобиографию", category: "Творчество", difficulty: 3, unlockLevel: 4 },
    { id: 621, text: "Написать картину маслом", category: "Искусство", difficulty: 3, unlockLevel: 4 },
    { id: 622, text: "Выступить на сцене", category: "Искусство", difficulty: 3, unlockLevel: 4 },
    { id: 623, text: "Сделать скульптуру 50+ см", category: "Искусство", difficulty: 3, unlockLevel: 4 },
    { id: 624, text: "Написать портрет с натуры", category: "Искусство", difficulty: 3, unlockLevel: 4 },
    { id: 625, text: "Расписать футболку", category: "Искусство", difficulty: 3, unlockLevel: 4 },
    { id: 626, text: "Научиться играть на скрипке/флейте", category: "Искусство", difficulty: 3, unlockLevel: 4 },
    { id: 627, text: "Посетить Третьяковку", category: "Искусство", difficulty: 3, unlockLevel: 4 },
    { id: 628, text: "Посетить 10 выставок за год", category: "Искусство", difficulty: 3, unlockLevel: 4 },
    { id: 629, text: "Посмотреть 50 фильмов из топ-100", category: "Искусство", difficulty: 3, unlockLevel: 4 },
    { id: 630, text: "Сходить на балет в Мариинский", category: "Искусство", difficulty: 3, unlockLevel: 4 },
    { id: 631, text: "Посетить концерт симфонического оркестра", category: "Искусство", difficulty: 3, unlockLevel: 4 },
    { id: 632, text: "Создать рисунок мелом на асфальте", category: "Искусство", difficulty: 3, unlockLevel: 4 },
    { id: 633, text: "Участвовать в граффити-джеме", category: "Искусство", difficulty: 3, unlockLevel: 4 },
    { id: 634, text: "Сходить на фестиваль уличного искусства", category: "Искусство", difficulty: 3, unlockLevel: 4 },
    { id: 635, text: "Освоить народный промысел", category: "Искусство", difficulty: 3, unlockLevel: 4 },
    { id: 636, text: "Создать анимационный ролик", category: "Искусство", difficulty: 3, unlockLevel: 4 },
    { id: 637, text: "Научиться рисовать на планшете", category: "Искусство", difficulty: 3, unlockLevel: 4 },
    { id: 638, text: "Смонтировать музыкальный клип", category: "Искусство", difficulty: 3, unlockLevel: 4 },
    { id: 639, text: "Организовать домашнюю выставку", category: "Искусство", difficulty: 3, unlockLevel: 4 },
    { id: 640, text: "Написать рецензию на спектакль", category: "Искусство", difficulty: 3, unlockLevel: 4 },
    { id: 641, text: "Стать волонтёром на выставке", category: "Искусство", difficulty: 3, unlockLevel: 4 },
    { id: 642, text: "Собрать коллекцию художественных открыток", category: "Искусство", difficulty: 3, unlockLevel: 4 },
    { id: 643, text: "Сходить на перформанс современного искусства", category: "Искусство", difficulty: 3, unlockLevel: 4 },
    { id: 644, text: "Посетить оперу в историческом театре", category: "Искусство", difficulty: 3, unlockLevel: 4 },
    { id: 645, text: "Написать короткую пьесу", category: "Искусство", difficulty: 3, unlockLevel: 4 },
    { id: 646, text: "Сделать коллаж из вырезок", category: "Творчество", difficulty: 3, unlockLevel: 4 },
    { id: 647, text: "Организовать домашний концерт", category: "Творчество", difficulty: 3, unlockLevel: 4 },
    { id: 648, text: "Написать сценарий короткого фильма", category: "Творчество", difficulty: 3, unlockLevel: 4 },
    { id: 649, text: "Придумать игру и создать прототип", category: "Творчество", difficulty: 3, unlockLevel: 4 },
    { id: 650, text: "Создать блог на неделю", category: "Творчество", difficulty: 3, unlockLevel: 4 },
    
    // ============================================================
    // УРОВЕНЬ 5 — МАСТЕРСТВО
    // ============================================================
    { id: 651, text: "Написать книгу о своих путешествиях", category: "Творчество", difficulty: 4, unlockLevel: 5 },
    { id: 652, text: "Создать семейный герб", category: "Творчество", difficulty: 4, unlockLevel: 5 },
    { id: 653, text: "Сделать домашний кинозал", category: "Дом и быт", difficulty: 4, unlockLevel: 5 },
    { id: 654, text: "Научиться делать сыроварение", category: "Кулинария", difficulty: 4, unlockLevel: 5 },
    { id: 655, text: "Попробовать себя в стендапе", category: "Творчество", difficulty: 4, unlockLevel: 5 },
    { id: 656, text: "Сделать репортаж о важном событии", category: "Медиа и информация", difficulty: 4, unlockLevel: 5 },
    { id: 657, text: "Провести мастер-класс для 10+ человек", category: "Навыки и саморазвитие", difficulty: 4, unlockLevel: 5 },
    { id: 658, text: "Принять участие в хакатоне", category: "Навыки и саморазвитие", difficulty: 4, unlockLevel: 5 },
    { id: 659, text: "Сделать сложный проект своими руками", category: "Творчество", difficulty: 4, unlockLevel: 5 },
    { id: 660, text: "Написать книгу за 30 дней", category: "Творчество", difficulty: 4, unlockLevel: 5 },
    { id: 661, text: "Создать образовательный курс", category: "Обучение и курсы", difficulty: 4, unlockLevel: 5 },
    { id: 662, text: "Написать мемуары", category: "Творчество", difficulty: 4, unlockLevel: 5 },
    { id: 663, text: "Создать первый в мире рецепт", category: "Кулинария", difficulty: 4, unlockLevel: 5 },
    { id: 664, text: "Организовать фестиваль", category: "Гостеприимство", difficulty: 4, unlockLevel: 5 },
    { id: 665, text: "Сделать научное открытие", category: "Навыки и саморазвитие", difficulty: 4, unlockLevel: 5 },
    { id: 666, text: "Написать бестселлер", category: "Творчество", difficulty: 4, unlockLevel: 5 },
    { id: 667, text: "Создать AI-агента", category: "Навыки и саморазвитие", difficulty: 4, unlockLevel: 5 },
    { id: 668, text: "Провести TEDx-выступление", category: "Навыки и саморазвитие", difficulty: 4, unlockLevel: 5 },
    { id: 669, text: "Стать автором учебника", category: "Обучение и курсы", difficulty: 4, unlockLevel: 5 },
    { id: 670, text: "Создать глобальное сообщество", category: "Отношения и любовь", difficulty: 4, unlockLevel: 5 },
    { id: 671, text: "Оставить след в истории", category: "Один раз в жизни", difficulty: 4, unlockLevel: 5 },
    { id: 672, text: "Прожить жизнь так, чтобы не было стыдно перед внуками", category: "Один раз в жизни", difficulty: 4, unlockLevel: 5 },
    { id: 673, text: "Сделать свой первый фильм", category: "Творчество", difficulty: 4, unlockLevel: 5 },
    { id: 674, text: "Выпустить свой альбом (музыка, стихи)", category: "Творчество", difficulty: 4, unlockLevel: 5 },
    { id: 675, text: "Открыть свою галерею", category: "Искусство", difficulty: 4, unlockLevel: 5 },
    { id: 676, text: "Создать новый жанр искусства", category: "Искусство", difficulty: 4, unlockLevel: 5 },
    { id: 677, text: "Организовать международную выставку", category: "Искусство", difficulty: 4, unlockLevel: 5 },
    { id: 678, text: "Стать художником-реставратором", category: "Искусство", difficulty: 4, unlockLevel: 5 },
    { id: 679, text: "Создать арт-объект в общественном месте", category: "Искусство", difficulty: 4, unlockLevel: 5 },
    { id: 680, text: "Провести арт-терапию для людей", category: "Волонтёрство", difficulty: 4, unlockLevel: 5 },
    { id: 681, text: "Создать музыкальный инструмент", category: "Творчество", difficulty: 4, unlockLevel: 5 },
    { id: 682, text: "Научиться играть на редком инструменте", category: "Искусство", difficulty: 4, unlockLevel: 5 },
    { id: 683, text: "Написать оперу", category: "Искусство", difficulty: 4, unlockLevel: 5 },
    { id: 684, text: "Создать танцевальную постановку", category: "Искусство", difficulty: 4, unlockLevel: 5 },
    { id: 685, text: "Стать наставником в творчестве", category: "Навыки и саморазвитие", difficulty: 4, unlockLevel: 5 },
    { id: 686, text: "Создать творческую мастерскую", category: "Творчество", difficulty: 4, unlockLevel: 5 },
    { id: 687, text: "Написать книгу стихов", category: "Творчество", difficulty: 4, unlockLevel: 5 },
    { id: 688, text: "Создать авторскую методику обучения", category: "Навыки и саморазвитие", difficulty: 4, unlockLevel: 5 },
    { id: 689, text: "Организовать международный фестиваль", category: "Гостеприимство", difficulty: 4, unlockLevel: 5 },
    { id: 690, text: "Стать художником года", category: "Искусство", difficulty: 4, unlockLevel: 5 },
    { id: 691, text: "Создать бренд своей одежды", category: "Творчество", difficulty: 4, unlockLevel: 5 },
    { id: 692, text: "Написать и поставить мюзикл", category: "Искусство", difficulty: 4, unlockLevel: 5 },
    { id: 693, text: "Создать виртуальную галерею", category: "Искусство", difficulty: 4, unlockLevel: 5 },
    { id: 694, text: "Освоить искусство кулинарного дизайна", category: "Кулинария", difficulty: 4, unlockLevel: 5 },
    { id: 695, text: "Создать серию иллюстраций к книге", category: "Творчество", difficulty: 4, unlockLevel: 5 },
    { id: 696, text: "Стать главным редактором журнала", category: "Медиа и информация", difficulty: 4, unlockLevel: 5 },
    { id: 697, text: "Создать мультфильм", category: "Творчество", difficulty: 4, unlockLevel: 5 },
    { id: 698, text: "Провести лекцию о творчестве", category: "Навыки и саморазвитие", difficulty: 4, unlockLevel: 5 },
    { id: 699, text: "Сделать инсталляцию для музея", category: "Искусство", difficulty: 4, unlockLevel: 5 },
    { id: 700, text: "Воплотить детскую мечту", category: "Один раз в жизни", difficulty: 4, unlockLevel: 5 }
];

export default tasks;