// packages/fishing.js
// ============================================================
// ПАКЕТ "РЫБАЛКА И ОХОТА" — 100 дел для любителей природы
// Уровень открытия: 5
// ============================================================

export const tasks = [
    // ============================================================
    // УРОВЕНЬ 5 — ОСНОВЫ РЫБАЛКИ
    // ============================================================
    { id: 901, text: "Поймать рыбу в реке, озере и море", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 902, text: "Поймать и отпустить хищную рыбу", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 903, text: "Съездить на зимнюю рыбалку", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 904, text: "Приготовить уху на костре", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 905, text: "Побывать на охоте", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 906, text: "Собрать полную корзину грибов", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 907, text: "Собрать лесные ягоды", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 908, text: "Найти и собрать съедобные дикоросы", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 909, text: "Замариновать грибы собственного сбора", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 910, text: "Поймать рыбу на спиннинг", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 911, text: "Поймать рыбу в горной реке", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 912, text: "Засолить рыбу собственного улова", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 913, text: "Поймать рыбу ночью с фонарём", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 914, text: "Найти и опознать 10 видов грибов", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 915, text: "Поймать рыбу на поплавочную удочку", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 916, text: "Собрать коллекцию рыбацких снастей", category: "Коллекционирование", difficulty: 3, unlockLevel: 5 },
    { id: 917, text: "Научиться вязать рыболовные узлы", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 918, text: "Сделать рыболовную снасть своими руками", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 919, text: "Провести день на рыбалке с семьёй", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 920, text: "Сфотографировать свой улов", category: "Фотография", difficulty: 3, unlockLevel: 5 },
    { id: 921, text: "Сварить уху на костре", category: "Кулинария", difficulty: 3, unlockLevel: 5 },
    { id: 922, text: "Научиться отличать съедобные грибы от ядовитых", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 923, text: "Собрать полную корзину ягод", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 924, text: "Сделать коптильню для рыбы", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 925, text: "Засолить икру", category: "Кулинария", difficulty: 3, unlockLevel: 5 },
    { id: 926, text: "Поймать рыбу на блесну", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 927, text: "Научиться делать рыболовные приманки", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 928, text: "Провести соревнование по рыбалке", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 929, text: "Съездить на рыбалку в другой регион", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 930, text: "Сделать фотоальбом о рыбалке", category: "Фотография", difficulty: 3, unlockLevel: 5 },
    { id: 931, text: "Научиться делать лодку из подручных материалов", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 932, text: "Установить рыбацкую палатку", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 933, text: "Провести ночь на рыбалке", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 934, text: "Поймать рыбу на мормышку", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 935, text: "Научиться определять места клёва", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 936, text: "Собрать комплект рыболова-любителя", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 937, text: "Поймать рыбу на донку", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 938, text: "Сделать копчёную рыбу", category: "Кулинария", difficulty: 3, unlockLevel: 5 },
    { id: 939, text: "Научиться делать рыболовную сеть", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 940, text: "Поймать рыбу на живца", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 941, text: "Съездить на рыбалку на 2 дня", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 942, text: "Научиться делать удочку своими руками", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 943, text: "Поймать 10 видов рыб", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 944, text: "Сделать рыболовный журнал", category: "Творчество", difficulty: 3, unlockLevel: 5 },
    { id: 945, text: "Провести мастер-класс по рыбалке", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 946, text: "Собрать коллекцию рыболовных блёсен", category: "Коллекционирование", difficulty: 3, unlockLevel: 5 },
    { id: 947, text: "Научиться определять погоду по рыбе", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 948, text: "Поймать трофейную рыбу", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    { id: 949, text: "Сделать карту рыболовных мест", category: "Городские исследования", difficulty: 3, unlockLevel: 5 },
    { id: 950, text: "Стать экспертом в рыболовстве", category: "Рыбалка и охота", difficulty: 3, unlockLevel: 5 },
    
    // ============================================================
    // УРОВЕНЬ 6 — МАСТЕР РЫБАЛКИ
    // ============================================================
    { id: 951, text: "Поймать рыбу весом больше рекорда", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 952, text: "Найти и опознать 20 видов грибов", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 953, text: "Поймать рыбу в горной реке 3+ категории", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 954, text: "Собрать коллекцию из 20 рыболовных приманок", category: "Коллекционирование", difficulty: 4, unlockLevel: 6 },
    { id: 955, text: "Приготовить 5 блюд из рыбы собственного улова", category: "Кулинария", difficulty: 4, unlockLevel: 6 },
    { id: 956, text: "Провести неделю на рыбалке", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 957, text: "Сделать лодку своими руками", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 958, text: "Поймать рыбу на 5 разных снастей", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 959, text: "Создать рыболовный клуб", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 960, text: "Организовать рыболовный фестиваль", category: "Гостеприимство", difficulty: 4, unlockLevel: 6 },
    { id: 961, text: "Поймать рыбу в 3 разных морях", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 962, text: "Сделать коптильню для рыбы", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 963, text: "Научиться делать рыболовные сети", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 964, text: "Поймать рыбу на кастинговую сеть", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 965, text: "Съездить на рыбалку в 5 регионов", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 966, text: "Сделать рыболовный блог", category: "Медиа и информация", difficulty: 4, unlockLevel: 6 },
    { id: 967, text: "Научиться делать консервы из рыбы", category: "Кулинария", difficulty: 4, unlockLevel: 6 },
    { id: 968, text: "Поймать рыбу на муху", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 969, text: "Собрать коллекцию воблеров", category: "Коллекционирование", difficulty: 4, unlockLevel: 6 },
    { id: 970, text: "Стать мастером спорта по рыболовству", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 971, text: "Поймать рыбу на спиннинг 10+ кг", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 972, text: "Научиться делать прикормку", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 973, text: "Провести рыболовный турнир", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 974, text: "Сделать карту рыболовных мест области", category: "Городские исследования", difficulty: 4, unlockLevel: 6 },
    { id: 975, text: "Научиться делать рыболовные поводки", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 976, text: "Поймать рыбу на фидер", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 977, text: "Сделать рыболовный костюм", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 978, text: "Поймать 20 разных видов рыб", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 979, text: "Научиться определять возраст рыбы", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 980, text: "Сделать рыболовную энциклопедию", category: "Творчество", difficulty: 4, unlockLevel: 6 },
    { id: 981, text: "Поймать рыбу на блесну в горной реке", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 982, text: "Научиться делать рыболовные грузила", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 983, text: "Провести неделю в охотничьем хозяйстве", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 984, text: "Сделать охотничий домик", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 985, text: "Научиться делать капканы", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 986, text: "Поймать дичь на охоте", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 987, text: "Сделать чучело утки", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 988, text: "Научиться делать охотничьи приманки", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 989, text: "Собрать коллекцию охотничьих трофеев", category: "Коллекционирование", difficulty: 4, unlockLevel: 6 },
    { id: 990, text: "Стать охотником-профессионалом", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 991, text: "Провести охотничий сезон", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 992, text: "Научиться делать охотничьи ножи", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 993, text: "Поймать трофейного кабана", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 994, text: "Сделать фотоальбом охотничьих трофеев", category: "Фотография", difficulty: 4, unlockLevel: 6 },
    { id: 995, text: "Научиться делать охотничьи ловушки", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 996, text: "Собрать коллекцию охотничьих ружей", category: "Коллекционирование", difficulty: 4, unlockLevel: 6 },
    { id: 997, text: "Стать егерем", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 998, text: "Провести охотничью экскурсию", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 999, text: "Научиться делать охотничьи свистки", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 },
    { id: 1000, text: "Стать легендой рыбалки и охоты", category: "Рыбалка и охота", difficulty: 4, unlockLevel: 6 }
];

export default tasks;