// packages/health.js
// ============================================================
// ПАКЕТ "СПОРТ И ЗДОРОВЬЕ" — 100 ЗОЖ-дел
// Уровень открытия: 3
// ============================================================

export const tasks = [
    // ============================================================
    // УРОВЕНЬ 3 — ЗДОРОВЫЕ ПРИВЫЧКИ
    // ============================================================
    { id: 301, text: "Сделать зарядку 10 минут", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 302, text: "Пробежать 1 км", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 303, text: "Сделать 30 отжиманий", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 304, text: "Принять контрастный душ", category: "Красота и уход", difficulty: 2, unlockLevel: 3 },
    { id: 305, text: "Провести день без сахара", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 306, text: "Сделать 100 шагов по траве босиком", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 307, text: "Провести 10 минут на свежем воздухе", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 308, text: "Сделать массаж стоп", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 309, text: "Выпить 2 литра воды", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 310, text: "Сделать 10 минут йоги", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 311, text: "Попробовать интервальное голодание (16/8)", category: "Биохакинг", difficulty: 2, unlockLevel: 3 },
    { id: 312, text: "Сделать план тренировок на неделю", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 313, text: "Отжаться 50 раз подряд", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 314, text: "Выполнить комплекс растяжки", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 315, text: "Прогуляться 30 минут", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 316, text: "Научиться правильно дышать (диафрагмальное дыхание)", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 317, text: "Сделать 50 приседаний", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 318, text: "Научиться делать стойку на голове", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 319, text: "Пройти 5 км пешком", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 320, text: "Сделать массаж спины", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 321, text: "Провести день без кофе", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 322, text: "Поспать 8 часов", category: "Сон и восстановление", difficulty: 2, unlockLevel: 3 },
    { id: 323, text: "Сделать утреннюю пробежку", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 324, text: "Научиться делать самомассаж шеи", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 325, text: "Пройти чекап у терапевта", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 326, text: "Сделать 100 отжиманий за день", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 327, text: "Попробовать сухое голодание (1 день)", category: "Биохакинг", difficulty: 2, unlockLevel: 3 },
    { id: 328, text: "Научиться измерять давление", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 329, text: "Пройти йога-класс", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 330, text: "Сделать комплекс упражнений для пресса", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 331, text: "Провести день без телефона", category: "Цифровая гигиена", difficulty: 2, unlockLevel: 3 },
    { id: 332, text: "Научиться плавать кролем", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 333, text: "Сделать чек-ап у стоматолога", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 334, text: "Вставать без будильника 7 дней", category: "Сон и восстановление", difficulty: 2, unlockLevel: 3 },
    { id: 335, text: "Научиться делать упражнение «планка» 1 минуту", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 336, text: "Пройти генетический тест", category: "Биохакинг", difficulty: 2, unlockLevel: 3 },
    { id: 337, text: "Убрать одну вредную привычку", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 338, text: "Научиться плавать брассом", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 339, text: "Пройти курс лечебного голодания", category: "Биохакинг", difficulty: 2, unlockLevel: 3 },
    { id: 340, text: "Выполнить 100 приседаний за раз", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 341, text: "Провести месяц без кофе", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 342, text: "Выучить комплекс утренней зарядки", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 343, text: "Пробежать 5 км", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 344, text: "Сделать прививки по календарю", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 345, text: "Провести месяц без алкоголя", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 346, text: "Научиться медитировать 10 минут", category: "Психология", difficulty: 2, unlockLevel: 3 },
    { id: 347, text: "Сделать дыхательную гимнастику", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 348, text: "Пройти чекап у эндокринолога", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 349, text: "Попробовать скандинавскую ходьбу", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 350, text: "Научиться делать упражнение «берпи»", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    
    // ============================================================
    // УРОВЕНЬ 4 — ЗДОРОВЫЙ ОБРАЗ ЖИЗНИ
    // ============================================================
    { id: 351, text: "Пройти полное медицинское обследование", category: "Здоровье и тело", difficulty: 2, unlockLevel: 4 },
    { id: 352, text: "Научиться бегать 10 км", category: "Здоровье и тело", difficulty: 3, unlockLevel: 4 },
    { id: 353, text: "Попробовать недельное голодание", category: "Биохакинг", difficulty: 3, unlockLevel: 4 },
    { id: 354, text: "Освоить дыхательную практику", category: "Здоровье и тело", difficulty: 3, unlockLevel: 4 },
    { id: 355, text: "Провести месяц без алкоголя", category: "Здоровье и тело", difficulty: 3, unlockLevel: 4 },
    { id: 356, text: "Отжиматься 100 раз подряд", category: "Здоровье и тело", difficulty: 3, unlockLevel: 4 },
    { id: 357, text: "Высыпаться 7 дней подряд", category: "Сон и восстановление", difficulty: 3, unlockLevel: 4 },
    { id: 358, text: "Завести привычку контрастного душа", category: "Красота и уход", difficulty: 3, unlockLevel: 4 },
    { id: 359, text: "Пройти курс массажа", category: "Здоровье и тело", difficulty: 3, unlockLevel: 4 },
    { id: 360, text: "Спать без подушки неделю", category: "Сон и восстановление", difficulty: 3, unlockLevel: 4 },
    { id: 361, text: "Пройти курс психотерапии", category: "Психология", difficulty: 3, unlockLevel: 4 },
    { id: 362, text: "Научиться плавать кролем 1 км", category: "Здоровье и тело", difficulty: 3, unlockLevel: 4 },
    { id: 363, text: "Научиться вставать без будильника", category: "Сон и восстановление", difficulty: 3, unlockLevel: 4 },
    { id: 364, text: "Сделать план тренировок на год", category: "Здоровье и тело", difficulty: 3, unlockLevel: 4 },
    { id: 365, text: "Пройти чекап у эндокринолога", category: "Здоровье и тело", difficulty: 3, unlockLevel: 4 },
    { id: 366, text: "Попробовать сухое голодание (2 дня)", category: "Биохакинг", difficulty: 3, unlockLevel: 4 },
    { id: 367, text: "Пройти генетический тест + интерпретация", category: "Биохакинг", difficulty: 3, unlockLevel: 4 },
    { id: 368, text: "Научиться правильно падать", category: "Самооборона", difficulty: 3, unlockLevel: 4 },
    { id: 369, text: "Освоить приём освобождения от захвата", category: "Самооборона", difficulty: 3, unlockLevel: 4 },
    { id: 370, text: "Пройти курсы тактической медицины", category: "Самооборона", difficulty: 3, unlockLevel: 4 },
    { id: 371, text: "Отработать сценарий нападения в подъезде", category: "Самооборона", difficulty: 3, unlockLevel: 4 },
    { id: 372, text: "Собрать тревожный рюкзак", category: "Самооборона", difficulty: 3, unlockLevel: 4 },
    { id: 373, text: "Научиться разжигать костёр в любую погоду", category: "Самооборона", difficulty: 3, unlockLevel: 4 },
    { id: 374, text: "Пройти курс первой помощи", category: "Самооборона", difficulty: 3, unlockLevel: 4 },
    { id: 375, text: "Научиться делать искусственное дыхание", category: "Самооборона", difficulty: 3, unlockLevel: 4 },
    
    // ============================================================
    // УРОВЕНЬ 5 — БИОХАКИНГ И ПРОДВИНУТОЕ ЗДОРОВЬЕ
    // ============================================================
    { id: 376, text: "Сдать расширенный генетический тест", category: "Биохакинг", difficulty: 4, unlockLevel: 5 },
    { id: 377, text: "Испытать ноотропы (под контролем врача)", category: "Биохакинг", difficulty: 4, unlockLevel: 5 },
    { id: 378, text: "Пройти холотропное дыхание", category: "Биохакинг", difficulty: 4, unlockLevel: 5 },
    { id: 379, text: "Научиться входить в гипнагогическое состояние", category: "Биохакинг", difficulty: 4, unlockLevel: 5 },
    { id: 380, text: "Попробовать интервальное голодание месяц", category: "Биохакинг", difficulty: 4, unlockLevel: 5 },
    { id: 381, text: "Научиться отслеживать биоритмы", category: "Биохакинг", difficulty: 4, unlockLevel: 5 },
    { id: 382, text: "Попробовать криотерапию", category: "Биохакинг", difficulty: 4, unlockLevel: 5 },
    { id: 383, text: "Заморозить стволовые клетки", category: "Биохакинг", difficulty: 4, unlockLevel: 5 },
    { id: 384, text: "Пройти курс биохакинга", category: "Биохакинг", difficulty: 4, unlockLevel: 5 },
    { id: 385, text: "Попробовать ночную терапию светом", category: "Биохакинг", difficulty: 4, unlockLevel: 5 },
    { id: 386, text: "Использовать нейроинтерфейс", category: "Биохакинг", difficulty: 4, unlockLevel: 5 },
    { id: 387, text: "Сдать тест на микробиом кишечника", category: "Биохакинг", difficulty: 4, unlockLevel: 5 },
    { id: 388, text: "Научиться измерять стресс по пульсу", category: "Биохакинг", difficulty: 4, unlockLevel: 5 },
    { id: 389, text: "Использовать tDCS (стимуляция мозга)", category: "Биохакинг", difficulty: 4, unlockLevel: 5 },
    { id: 390, text: "Попробовать терапию красным светом", category: "Биохакинг", difficulty: 4, unlockLevel: 5 },
    { id: 391, text: "Научиться управлять температурой тела", category: "Биохакинг", difficulty: 4, unlockLevel: 5 },
    { id: 392, text: "Посетить конференцию по биохакингу", category: "Биохакинг", difficulty: 4, unlockLevel: 5 },
    { id: 393, text: "Создать программу максимальной продуктивности", category: "Биохакинг", difficulty: 4, unlockLevel: 5 },
    { id: 394, text: "Попробовать сенсорную депривацию", category: "Биохакинг", difficulty: 4, unlockLevel: 5 },
    { id: 395, text: "Использовать нейрофидбек", category: "Биохакинг", difficulty: 4, unlockLevel: 5 },
    { id: 396, text: "Пройти курс осознанного питания", category: "Биохакинг", difficulty: 4, unlockLevel: 5 },
    { id: 397, text: "Научиться входить в состояние «потока»", category: "Биохакинг", difficulty: 4, unlockLevel: 5 },
    { id: 398, text: "Попробовать экспозиционную терапию", category: "Биохакинг", difficulty: 4, unlockLevel: 5 },
    { id: 399, text: "Пройти чек-ап всего организма", category: "Здоровье и тело", difficulty: 4, unlockLevel: 5 },
    { id: 400, text: "Достичь идеального веса", category: "Здоровье и тело", difficulty: 4, unlockLevel: 5 }
];

export default tasks;