// packages/nature.js
// ============================================================
// ПАКЕТ "ПРИРОДА" — 100 дел на свежем воздухе
// Уровень открытия: 3
// ============================================================

export const tasks = [
    // ============================================================
    // УРОВЕНЬ 3 — ЗНАКОМСТВО С ПРИРОДОЙ
    // ============================================================
    { id: 501, text: "Собрать гербарий из 10 листьев", category: "Гербарий и ботаника", difficulty: 2, unlockLevel: 3 },
    { id: 502, text: "Собрать гербарий из 5 папоротников", category: "Гербарий и ботаника", difficulty: 2, unlockLevel: 3 },
    { id: 503, text: "Сфотографировать цветок из Красной книги", category: "Гербарий и ботаника", difficulty: 2, unlockLevel: 3 },
    { id: 504, text: "Создать «гербарий запахов»", category: "Гербарий и ботаника", difficulty: 2, unlockLevel: 3 },
    { id: 505, text: "Оформить гербарий в рамку", category: "Гербарий и ботаника", difficulty: 2, unlockLevel: 3 },
    { id: 506, text: "Собрать коллекцию шишек", category: "Гербарий и ботаника", difficulty: 2, unlockLevel: 3 },
    { id: 507, text: "Собрать коллекцию семян", category: "Гербарий и ботаника", difficulty: 2, unlockLevel: 3 },
    { id: 508, text: "Вырастить зелень на подоконнике", category: "Садоводство и огород", difficulty: 2, unlockLevel: 3 },
    { id: 509, text: "Посадить дерево", category: "Садоводство и огород", difficulty: 2, unlockLevel: 3 },
    { id: 510, text: "Вырастить цветок из семечка", category: "Садоводство и огород", difficulty: 2, unlockLevel: 3 },
    { id: 511, text: "Вырастить редис", category: "Садоводство и огород", difficulty: 2, unlockLevel: 3 },
    { id: 512, text: "Сделать компост из отходов", category: "Садоводство и огород", difficulty: 2, unlockLevel: 3 },
    { id: 513, text: "Вырастить пряные травы", category: "Садоводство и огород", difficulty: 2, unlockLevel: 3 },
    { id: 514, text: "Собрать берёзовый сок весной", category: "Садоводство и огород", difficulty: 2, unlockLevel: 3 },
    { id: 515, text: "Сделать грядку на балконе", category: "Садоводство и огород", difficulty: 2, unlockLevel: 3 },
    { id: 516, text: "Собрать полную корзину грибов", category: "Рыбалка и охота", difficulty: 2, unlockLevel: 3 },
    { id: 517, text: "Собрать лесные ягоды", category: "Рыбалка и охота", difficulty: 2, unlockLevel: 3 },
    { id: 518, text: "Найти и собрать съедобные дикоросы", category: "Рыбалка и охота", difficulty: 2, unlockLevel: 3 },
    { id: 519, text: "Замариновать грибы собственного сбора", category: "Рыбалка и охота", difficulty: 2, unlockLevel: 3 },
    { id: 520, text: "Покормить птиц зимой", category: "Волонтёрство", difficulty: 2, unlockLevel: 3 },
    { id: 521, text: "Построить скворечник", category: "Волонтёрство", difficulty: 2, unlockLevel: 3 },
    { id: 522, text: "Сделать кормушку для белок", category: "Волонтёрство", difficulty: 2, unlockLevel: 3 },
    { id: 523, text: "Провести день в лесу без телефона", category: "Эмоции и впечатления", difficulty: 2, unlockLevel: 3 },
    { id: 524, text: "Встретить рассвет в лесу", category: "Эмоции и впечатления", difficulty: 2, unlockLevel: 3 },
    { id: 525, text: "Найти и опознать 10 видов грибов", category: "Рыбалка и охота", difficulty: 2, unlockLevel: 3 },
    { id: 526, text: "Собрать коллекцию камней", category: "Коллекционирование", difficulty: 2, unlockLevel: 3 },
    { id: 527, text: "Найти следы животных в лесу", category: "Рыбалка и охота", difficulty: 2, unlockLevel: 3 },
    { id: 528, text: "Понаблюдать за птицами", category: "Эмоции и впечатления", difficulty: 2, unlockLevel: 3 },
    { id: 529, text: "Сделать фото лесного озера", category: "Фотография", difficulty: 2, unlockLevel: 3 },
    { id: 530, text: "Посадить 5 деревьев", category: "Садоводство и огород", difficulty: 2, unlockLevel: 3 },
    { id: 531, text: "Создать цветник на балконе", category: "Садоводство и огород", difficulty: 2, unlockLevel: 3 },
    { id: 532, text: "Научиться различать деревья по коре", category: "Гербарий и ботаника", difficulty: 2, unlockLevel: 3 },
    { id: 533, text: "Собрать букет полевых цветов", category: "Эмоции и впечатления", difficulty: 2, unlockLevel: 3 },
    { id: 534, text: "Провести ночь в палатке", category: "Эмоции и впечатления", difficulty: 2, unlockLevel: 3 },
    { id: 535, text: "Сделать костёр без спичек", category: "Самооборона", difficulty: 2, unlockLevel: 3 },
    { id: 536, text: "Научиться ориентироваться по звёздам", category: "Астрономия и космос", difficulty: 2, unlockLevel: 3 },
    { id: 537, text: "Собрать коллекцию минералов", category: "Коллекционирование", difficulty: 2, unlockLevel: 3 },
    { id: 538, text: "Сделать фото животных в естественной среде", category: "Фотография", difficulty: 2, unlockLevel: 3 },
    { id: 539, text: "Провести пикник в лесу", category: "Гостеприимство", difficulty: 2, unlockLevel: 3 },
    { id: 540, text: "Устроить лесную фотосессию", category: "Фотография", difficulty: 2, unlockLevel: 3 },
    { id: 541, text: "Собрать лекарственные травы", category: "Гербарий и ботаника", difficulty: 2, unlockLevel: 3 },
    { id: 542, text: "Сделать лесную полянку в горшке", category: "Садоводство и огород", difficulty: 2, unlockLevel: 3 },
    { id: 543, text: "Покататься на велосипеде по лесной тропе", category: "Здоровье и тело", difficulty: 2, unlockLevel: 3 },
    { id: 544, text: "Провести день на озере", category: "Эмоции и впечатления", difficulty: 2, unlockLevel: 3 },
    { id: 545, text: "Сделать гербарий из цветов", category: "Гербарий и ботаника", difficulty: 2, unlockLevel: 3 },
    { id: 546, text: "Научиться делать венки из трав", category: "Творчество", difficulty: 2, unlockLevel: 3 },
    { id: 547, text: "Посадить тюльпаны", category: "Садоводство и огород", difficulty: 2, unlockLevel: 3 },
    { id: 548, text: "Сделать фото лесной поляны", category: "Фотография", difficulty: 2, unlockLevel: 3 },
    { id: 549, text: "Собрать коллекцию желудей", category: "Коллекционирование", difficulty: 2, unlockLevel: 3 },
    { id: 550, text: "Найти самый старый дуб в парке", category: "Городские исследования", difficulty: 2, unlockLevel: 3 },
    
    // ============================================================
    // УРОВЕНЬ 4 — УХОД ЗА ПРИРОДОЙ
    // ============================================================
    { id: 551, text: "Создать мини-сад на подоконнике", category: "Садоводство и огород", difficulty: 3, unlockLevel: 4 },
    { id: 552, text: "Вырастить помидоры на балконе", category: "Садоводство и огород", difficulty: 3, unlockLevel: 4 },
    { id: 553, text: "Сделать террариум", category: "Садоводство и огород", difficulty: 3, unlockLevel: 4 },
    { id: 554, text: "Участвовать в субботнике в лесу", category: "Волонтёрство", difficulty: 3, unlockLevel: 4 },
    { id: 555, text: "Посадить аллею деревьев", category: "Волонтёрство", difficulty: 3, unlockLevel: 4 },
    { id: 556, text: "Обустроить кормушку для птиц", category: "Волонтёрство", difficulty: 3, unlockLevel: 4 },
    { id: 557, text: "Сделать искусственное гнездо", category: "Волонтёрство", difficulty: 3, unlockLevel: 4 },
    { id: 558, text: "Провести экскурсию по лесу", category: "Волонтёрство", difficulty: 3, unlockLevel: 4 },
    { id: 559, text: "Создать экологическую тропу", category: "Волонтёрство", difficulty: 3, unlockLevel: 4 },
    { id: 560, text: "Организовать уборку водоёма", category: "Волонтёрство", difficulty: 3, unlockLevel: 4 },
    { id: 561, text: "Сделать фотокнигу о природе региона", category: "Фотография", difficulty: 3, unlockLevel: 4 },
    { id: 562, text: "Собрать коллекцию листьев всех деревьев региона", category: "Гербарий и ботаника", difficulty: 3, unlockLevel: 4 },
    { id: 563, text: "Вырастить овощи на балконе", category: "Садоводство и огород", difficulty: 3, unlockLevel: 4 },
    { id: 564, text: "Создать вертикальный сад", category: "Садоводство и огород", difficulty: 3, unlockLevel: 4 },
    { id: 565, text: "Провести неделю без пластика в лесу", category: "Экология", difficulty: 3, unlockLevel: 4 },
    { id: 566, text: "Сделать скворечник своими руками", category: "Волонтёрство", difficulty: 3, unlockLevel: 4 },
    { id: 567, text: "Организовать фестиваль садоводов", category: "Гостеприимство", difficulty: 3, unlockLevel: 4 },
    { id: 568, text: "Создать лесную библиотеку", category: "Волонтёрство", difficulty: 3, unlockLevel: 4 },
    { id: 569, text: "Посадить 100 деревьев", category: "Волонтёрство", difficulty: 3, unlockLevel: 4 },
    { id: 570, text: "Сделать парк для насекомых", category: "Садоводство и огород", difficulty: 3, unlockLevel: 4 },
    { id: 571, text: "Собрать и сохранить семена редких растений", category: "Гербарий и ботаника", difficulty: 3, unlockLevel: 4 },
    { id: 572, text: "Вырастить кактус из семян", category: "Садоводство и огород", difficulty: 3, unlockLevel: 4 },
    { id: 573, text: "Создать альбом с фотографиями природы", category: "Фотография", difficulty: 3, unlockLevel: 4 },
    { id: 574, text: "Провести мастер-класс по садоводству", category: "Навыки и саморазвитие", difficulty: 3, unlockLevel: 4 },
    { id: 575, text: "Организовать поход выходного дня", category: "Путешествия по России", difficulty: 3, unlockLevel: 4 },
    
    // ============================================================
    // УРОВЕНЬ 5 — ЗАЩИТА ПРИРОДЫ
    // ============================================================
    { id: 576, text: "Участвовать в лесопосадке", category: "Волонтёрство", difficulty: 4, unlockLevel: 5 },
    { id: 577, text: "Стать волонтёром заповедника", category: "Волонтёрство", difficulty: 4, unlockLevel: 5 },
    { id: 578, text: "Создать экопроект", category: "Экология", difficulty: 4, unlockLevel: 5 },
    { id: 579, text: "Обустроить источник с питьевой водой", category: "Экология", difficulty: 4, unlockLevel: 5 },
    { id: 580, text: "Провести экологический лагерь для детей", category: "Волонтёрство", difficulty: 4, unlockLevel: 5 },
    { id: 581, text: "Создать общественный огород", category: "Садоводство и огород", difficulty: 4, unlockLevel: 5 },
    { id: 582, text: "Собрать 100 кг мусора в лесу", category: "Волонтёрство", difficulty: 4, unlockLevel: 5 },
    { id: 583, text: "Посадить лес на 1 гектаре", category: "Волонтёрство", difficulty: 4, unlockLevel: 5 },
    { id: 584, text: "Создать экологическую тропу в парке", category: "Волонтёрство", difficulty: 4, unlockLevel: 5 },
    { id: 585, text: "Организовать городскую акцию по озеленению", category: "Волонтёрство", difficulty: 4, unlockLevel: 5 },
    { id: 586, text: "Создать фонд защиты природы", category: "Благотворительность", difficulty: 4, unlockLevel: 5 },
    { id: 587, text: "Провести экологический мониторинг", category: "Экология", difficulty: 4, unlockLevel: 5 },
    { id: 588, text: "Создать экологическую карту города", category: "Городские исследования", difficulty: 4, unlockLevel: 5 },
    { id: 589, text: "Организовать общественный сад", category: "Садоводство и огород", difficulty: 4, unlockLevel: 5 },
    { id: 590, text: "Стать экологическим активистом", category: "Волонтёрство", difficulty: 4, unlockLevel: 5 },
    { id: 591, text: "Создать питомник для растений", category: "Садоводство и огород", difficulty: 4, unlockLevel: 5 },
    { id: 592, text: "Организовать экологический фестиваль", category: "Волонтёрство", difficulty: 4, unlockLevel: 5 },
    { id: 593, text: "Сделать фотодокументацию 50 видов птиц", category: "Фотография", difficulty: 4, unlockLevel: 5 },
    { id: 594, text: "Создать гербарий из 100 растений", category: "Гербарий и ботаника", difficulty: 4, unlockLevel: 5 },
    { id: 595, text: "Провести экологический урок в школе", category: "Волонтёрство", difficulty: 4, unlockLevel: 5 },
    { id: 596, text: "Создать парк в своём районе", category: "Волонтёрство", difficulty: 4, unlockLevel: 5 },
    { id: 597, text: "Вырастить более 50 видов растений", category: "Садоводство и огород", difficulty: 4, unlockLevel: 5 },
    { id: 598, text: "Создать сайт о природе региона", category: "Медиа и информация", difficulty: 4, unlockLevel: 5 },
    { id: 599, text: "Организовать экологический проект в школе", category: "Волонтёрство", difficulty: 4, unlockLevel: 5 },
    { id: 600, text: "Стать послом экологии", category: "Волонтёрство", difficulty: 4, unlockLevel: 5 }
];

export default tasks;