// packages/relationships.js
// ============================================================
// ПАКЕТ "ОТНОШЕНИЯ" — 100 дел для близких и друзей
// Уровень открытия: 4
// ============================================================

export const tasks = [
    // ============================================================
    // УРОВЕНЬ 4 — ОСНОВЫ ОТНОШЕНИЙ
    // ============================================================
    { id: 801, text: "Сказать 'я люблю тебя' первым", category: "Отношения и любовь", difficulty: 2, unlockLevel: 4 },
    { id: 802, text: "Попросить прощения у обиженного", category: "Отношения и любовь", difficulty: 2, unlockLevel: 4 },
    { id: 803, text: "Простить того, кто не просит", category: "Отношения и любовь", difficulty: 2, unlockLevel: 4 },
    { id: 804, text: "Организовать родителям сюрприз", category: "Отношения и любовь", difficulty: 2, unlockLevel: 4 },
    { id: 805, text: "Сходить на свидание без телефона", category: "Отношения и любовь", difficulty: 2, unlockLevel: 4 },
    { id: 806, text: "Прожить с партнёром «неделю как в начале»", category: "Отношения и любовь", difficulty: 2, unlockLevel: 4 },
    { id: 807, text: "Завести друга для откровенных разговоров", category: "Отношения и любовь", difficulty: 2, unlockLevel: 4 },
    { id: 808, text: "Написать благодарность учителю", category: "Отношения и любовь", difficulty: 2, unlockLevel: 4 },
    { id: 809, text: "Помочь незнакомцу бескорыстно", category: "Отношения и любовь", difficulty: 2, unlockLevel: 4 },
    { id: 810, text: "Взять ответственность за питомца", category: "Отношения и любовь", difficulty: 2, unlockLevel: 4 },
    { id: 811, text: "Сделать семейное древо", category: "Отношения и любовь", difficulty: 2, unlockLevel: 4 },
    { id: 812, text: "Создать семейную традицию", category: "Отношения и любовь", difficulty: 2, unlockLevel: 4 },
    { id: 813, text: "Сказать «нет» манипулятору", category: "Отношения и любовь", difficulty: 2, unlockLevel: 4 },
    { id: 814, text: "Приютить бездомное животное", category: "Отношения и любовь", difficulty: 2, unlockLevel: 4 },
    { id: 815, text: "Восстановить старую дружбу", category: "Отношения и любовь", difficulty: 2, unlockLevel: 4 },
    { id: 816, text: "Позвонить давнему другу", category: "Отношения и любовь", difficulty: 2, unlockLevel: 4 },
    { id: 817, text: "Написать письмо родителям", category: "Письма", difficulty: 2, unlockLevel: 4 },
    { id: 818, text: "Сделать комплимент 10 незнакомцам", category: "Отношения и любовь", difficulty: 2, unlockLevel: 4 },
    { id: 819, text: "Провести день без негатива", category: "Психология", difficulty: 2, unlockLevel: 4 },
    { id: 820, text: "Собрать всю семью за ужином", category: "Отношения и любовь", difficulty: 2, unlockLevel: 4 },
    { id: 821, text: "Подарить цветы без повода", category: "Отношения и любовь", difficulty: 2, unlockLevel: 4 },
    { id: 822, text: "Научиться слушать, а не слышать", category: "Психология", difficulty: 2, unlockLevel: 4 },
    { id: 823, text: "Выйти из зоны комфорта ради близкого", category: "Отношения и любовь", difficulty: 2, unlockLevel: 4 },
    { id: 824, text: "Сделать генеральную уборку по КонМари", category: "Дом и быт", difficulty: 2, unlockLevel: 4 },
    { id: 825, text: "Организовать систему хранения на год", category: "Дом и быт", difficulty: 2, unlockLevel: 4 },
    { id: 826, text: "Вырастить дома цветок", category: "Дом и быт", difficulty: 2, unlockLevel: 4 },
    { id: 827, text: "Создать уголок тишины", category: "Дом и быт", difficulty: 2, unlockLevel: 4 },
    { id: 828, text: "Отремонтировать старую мебель", category: "Дом и быт", difficulty: 2, unlockLevel: 4 },
    { id: 829, text: "Повесить на стену свою работу", category: "Дом и быт", difficulty: 2, unlockLevel: 4 },
    { id: 830, text: "Создать домашний бар", category: "Дом и быт", difficulty: 2, unlockLevel: 4 },
    { id: 831, text: "Организовать домашний архив", category: "Дом и быт", difficulty: 2, unlockLevel: 4 },
    { id: 832, text: "Купить хорошее постельное бельё", category: "Дом и быт", difficulty: 2, unlockLevel: 4 },
    { id: 833, text: "Создать домашнюю аптечку", category: "Дом и быт", difficulty: 2, unlockLevel: 4 },
    { id: 834, text: "Провести ревизию гардероба", category: "Дом и быт", difficulty: 2, unlockLevel: 4 },
    { id: 835, text: "Обустроить балкон как жилое пространство", category: "Дом и быт", difficulty: 2, unlockLevel: 4 },
    { id: 836, text: "Научиться штопать и пришивать пуговицы", category: "Дом и быт", difficulty: 2, unlockLevel: 4 },
    { id: 837, text: "Навести порядок на кухне", category: "Дом и быт", difficulty: 2, unlockLevel: 4 },
    { id: 838, text: "Украсить дом к празднику своими руками", category: "Дом и быт", difficulty: 2, unlockLevel: 4 },
    { id: 839, text: "Завести доску желаний на видном месте", category: "Дом и быт", difficulty: 2, unlockLevel: 4 },
    { id: 840, text: "Сделать уборку уровня «можно звать гостей»", category: "Дом и быт", difficulty: 2, unlockLevel: 4 },
    { id: 841, text: "Купить хорошие постельные принадлежности", category: "Дом и быт", difficulty: 2, unlockLevel: 4 },
    { id: 842, text: "Сделать ремонт в одной комнате", category: "Дом и быт", difficulty: 2, unlockLevel: 4 },
    { id: 843, text: "Завести домашнее растение из черенка", category: "Дом и быт", difficulty: 2, unlockLevel: 4 },
    { id: 844, text: "Сделать генеральную уборку", category: "Дом и быт", difficulty: 2, unlockLevel: 4 },
    { id: 845, text: "Организовать систему хранения", category: "Дом и быт", difficulty: 2, unlockLevel: 4 },
    { id: 846, text: "Создать уголок для чтения", category: "Дом и быт", difficulty: 2, unlockLevel: 4 },
    { id: 847, text: "Провести аудит гардероба", category: "Дом и быт", difficulty: 2, unlockLevel: 4 },
    { id: 848, text: "Обустроить рабочее место", category: "Дом и быт", difficulty: 2, unlockLevel: 4 },
    { id: 849, text: "Сделать уборку на балконе", category: "Дом и быт", difficulty: 2, unlockLevel: 4 },
    { id: 850, text: "Навести порядок в шкафах", category: "Дом и быт", difficulty: 2, unlockLevel: 4 },
    
    // ============================================================
    // УРОВЕНЬ 5 — ГЛУБОКИЕ ОТНОШЕНИЯ
    // ============================================================
    { id: 851, text: "Сделать предложение или признаться в любви первым", category: "Эмоции и впечатления", difficulty: 3, unlockLevel: 5 },
    { id: 852, text: "Влюбиться без памяти", category: "Один раз в жизни", difficulty: 3, unlockLevel: 5 },
    { id: 853, text: "Помочь тому, кто обидел", category: "Один раз в жизни", difficulty: 3, unlockLevel: 5 },
    { id: 854, text: "Пережить потрясение и остаться собой", category: "Один раз в жизни", difficulty: 3, unlockLevel: 5 },
    { id: 855, text: "Сказать «хватит» привычкам", category: "Один раз в жизни", difficulty: 3, unlockLevel: 5 },
    { id: 856, text: "Остаться одному в незнакомом городе на неделю", category: "Один раз в жизни", difficulty: 3, unlockLevel: 5 },
    { id: 857, text: "Попробовать то, что все запрещают (легально)", category: "Один раз в жизни", difficulty: 3, unlockLevel: 5 },
    { id: 858, text: "Перестать доказывать", category: "Один раз в жизни", difficulty: 3, unlockLevel: 5 },
    { id: 859, text: "Побыть счастливым без причины", category: "Один раз в жизни", difficulty: 3, unlockLevel: 5 },
    { id: 860, text: "Попросить помощи", category: "Один раз в жизни", difficulty: 3, unlockLevel: 5 },
    { id: 861, text: "Отказаться от чужой мечты", category: "Один раз в жизни", difficulty: 3, unlockLevel: 5 },
    { id: 862, text: "Подарить цветы незнакомцу", category: "Один раз в жизни", difficulty: 3, unlockLevel: 5 },
    { id: 863, text: "Начать жизнь с нуля", category: "Один раз в жизни", difficulty: 3, unlockLevel: 5 },
    { id: 864, text: "Защитить слабого, когда страшно", category: "Один раз в жизни", difficulty: 3, unlockLevel: 5 },
    { id: 865, text: "Сказать правду в лицо", category: "Один раз в жизни", difficulty: 3, unlockLevel: 5 },
    { id: 866, text: "Пережить предательство и не стать предателем", category: "Один раз в жизни", difficulty: 3, unlockLevel: 5 },
    { id: 867, text: "Сказать «спасибо» своему прошлому", category: "Один раз в жизни", difficulty: 3, unlockLevel: 5 },
    { id: 868, text: "Умереть для чужих ожиданий", category: "Один раз в жизни", difficulty: 3, unlockLevel: 5 },
    { id: 869, text: "Перестать ждать идеального момента", category: "Один раз в жизни", difficulty: 3, unlockLevel: 5 },
    { id: 870, text: "Побыть в роли того, кого осуждаешь", category: "Один раз в жизни", difficulty: 3, unlockLevel: 5 },
    { id: 871, text: "Сделать то, что не вписывается в образ", category: "Один раз в жизни", difficulty: 3, unlockLevel: 5 },
    { id: 872, text: "Сказать «нет» тому, кто манипулирует", category: "Один раз в жизни", difficulty: 3, unlockLevel: 5 },
    { id: 873, text: "Пойти на терапию и честно поработать", category: "Один раз в жизни", difficulty: 3, unlockLevel: 5 },
    { id: 874, text: "Простить себя за прошлые ошибки", category: "Один раз в жизни", difficulty: 3, unlockLevel: 5 },
    { id: 875, text: "Достичь финансовой свободы", category: "Финансы", difficulty: 3, unlockLevel: 5 },
    { id: 876, text: "Сменить нелюбимую работу на любимую", category: "Работа и карьера", difficulty: 3, unlockLevel: 5 },
    { id: 877, text: "Выйти на пассивный доход 50+%", category: "Финансы", difficulty: 3, unlockLevel: 5 },
    { id: 878, text: "Купить жильё", category: "Финансы", difficulty: 3, unlockLevel: 5 },
    { id: 879, text: "Заработать фантастическую сумму", category: "Финансы", difficulty: 3, unlockLevel: 5 },
    { id: 880, text: "Инвестировать в стартап и получить прибыль", category: "Финансы", difficulty: 3, unlockLevel: 5 },
    { id: 881, text: "Создать семейную династию", category: "Отношения и любовь", difficulty: 3, unlockLevel: 5 },
    { id: 882, text: "Стать послом доброй воли", category: "Волонтёрство", difficulty: 3, unlockLevel: 5 },
    { id: 883, text: "Воплотить детскую мечту", category: "Один раз в жизни", difficulty: 3, unlockLevel: 5 },
    { id: 884, text: "Стать гражданином мира", category: "Отношения и любовь", difficulty: 3, unlockLevel: 5 },
    { id: 885, text: "Провести собственное исследование и опубликовать", category: "Навыки и саморазвитие", difficulty: 3, unlockLevel: 5 },
    { id: 886, text: "Создать семейную династию", category: "Отношения и любовь", difficulty: 3, unlockLevel: 5 },
    { id: 887, text: "Открыть школу или курсы", category: "Обучение и курсы", difficulty: 3, unlockLevel: 5 },
    { id: 888, text: "Стать послом доброй воли", category: "Волонтёрство", difficulty: 3, unlockLevel: 5 },
    { id: 889, text: "Воплотить детскую мечту", category: "Один раз в жизни", difficulty: 3, unlockLevel: 5 },
    { id: 890, text: "Написать бестселлер", category: "Творчество", difficulty: 3, unlockLevel: 5 },
    { id: 891, text: "Создать AI-агента", category: "Навыки и саморазвитие", difficulty: 3, unlockLevel: 5 },
    { id: 892, text: "Стать инвестором в стартапы", category: "Финансы", difficulty: 3, unlockLevel: 5 },
    { id: 893, text: "Провести TEDx-выступление", category: "Навыки и саморазвитие", difficulty: 3, unlockLevel: 5 },
    { id: 894, text: "Стать автором учебника", category: "Обучение и курсы", difficulty: 3, unlockLevel: 5 },
    { id: 895, text: "Основать экосистему", category: "Экология", difficulty: 3, unlockLevel: 5 },
    { id: 896, text: "Получить Нобелевскую премию", category: "Навыки и саморазвитие", difficulty: 3, unlockLevel: 5 },
    { id: 897, text: "Создать глобальное сообщество", category: "Отношения и любовь", difficulty: 3, unlockLevel: 5 },
    { id: 898, text: "Оставить след в истории", category: "Один раз в жизни", difficulty: 3, unlockLevel: 5 },
    { id: 899, text: "Достичь полной финансовой независимости", category: "Финансы", difficulty: 3, unlockLevel: 5 },
    { id: 900, text: "Прожить жизнь так, чтобы не было стыдно перед внуками", category: "Один раз в жизни", difficulty: 3, unlockLevel: 5 }
];

export default tasks;