// packages/selfdev.js
// ============================================================
// ПАКЕТ "САМОРАЗВИТИЕ" — 100 дел для роста и развития
// Уровень открытия: 4
// ============================================================

export const tasks = [
    // ============================================================
    // УРОВЕНЬ 4 — ОСНОВЫ САМОРАЗВИТИЯ
    // ============================================================
    { id: 701, text: "Выучить 10 слов на языке народов России", category: "Навыки и саморазвитие", difficulty: 2, unlockLevel: 4 },
    { id: 702, text: "Научиться играть 3 аккорда на гитаре", category: "Навыки и саморазвитие", difficulty: 2, unlockLevel: 4 },
    { id: 703, text: "Освоить слепую печать (10 слов/мин)", category: "Навыки и саморазвитие", difficulty: 2, unlockLevel: 4 },
    { id: 704, text: "Разобраться в основах инвестиций", category: "Финансы", difficulty: 2, unlockLevel: 4 },
    { id: 705, text: "Научиться делать искусственное дыхание", category: "Навыки и саморазвитие", difficulty: 2, unlockLevel: 4 },
    { id: 706, text: "Освоить разведение костра в лесу", category: "Навыки и саморазвитие", difficulty: 2, unlockLevel: 4 },
    { id: 707, text: "Выучить 10 фраз на жестовом языке", category: "Навыки и саморазвитие", difficulty: 2, unlockLevel: 4 },
    { id: 708, text: "Научиться трогаться на механике", category: "Навыки и саморазвитие", difficulty: 2, unlockLevel: 4 },
    { id: 709, text: "Освоить базовый видеомонтаж", category: "Навыки и саморазвитие", difficulty: 2, unlockLevel: 4 },
    { id: 710, text: "Научиться фотографировать в ручном режиме", category: "Навыки и саморазвитие", difficulty: 2, unlockLevel: 4 },
    { id: 711, text: "Научиться говорить 'нет'", category: "Навыки и саморазвитие", difficulty: 2, unlockLevel: 4 },
    { id: 712, text: "Освоить технику скорочтения", category: "Навыки и саморазвитие", difficulty: 2, unlockLevel: 4 },
    { id: 713, text: "Научиться медитировать 5 минут", category: "Навыки и саморазвитие", difficulty: 2, unlockLevel: 4 },
    { id: 714, text: "Разобраться в сортах кофе", category: "Навыки и саморазвитие", difficulty: 2, unlockLevel: 4 },
    { id: 715, text: "Научиться делать простой ремонт в доме", category: "Навыки и саморазвитие", difficulty: 2, unlockLevel: 4 },
    { id: 716, text: "Выучить 50 слов на языке народов России", category: "Навыки и саморазвитие", difficulty: 2, unlockLevel: 4 },
    { id: 717, text: "Освоить гончарное дело (слепить кружку)", category: "Навыки и саморазвитие", difficulty: 2, unlockLevel: 4 },
    { id: 718, text: "Научиться просыпаться без будильника 3 дня", category: "Навыки и саморазвитие", difficulty: 2, unlockLevel: 4 },
    { id: 719, text: "Освоить базовый дизайн интерьеров", category: "Обучение и курсы", difficulty: 2, unlockLevel: 4 },
    { id: 720, text: "Научиться работать в Figma", category: "Навыки и саморазвитие", difficulty: 2, unlockLevel: 4 },
    { id: 721, text: "Пройти курс тайм-менеджмента", category: "Обучение и курсы", difficulty: 2, unlockLevel: 4 },
    { id: 722, text: "Освоить базовую статистику в Excel", category: "Обучение и курсы", difficulty: 2, unlockLevel: 4 },
    { id: 723, text: "Пройти курсы по уходу за пожилыми", category: "Обучение и курсы", difficulty: 2, unlockLevel: 4 },
    { id: 724, text: "Получить права на квадроцикл", category: "Обучение и курсы", difficulty: 2, unlockLevel: 4 },
    { id: 725, text: "Научиться делать сайты на Tilda", category: "Обучение и курсы", difficulty: 2, unlockLevel: 4 },
    { id: 726, text: "Пройти курс по экологичному образу жизни", category: "Обучение и курсы", difficulty: 2, unlockLevel: 4 },
    { id: 727, text: "Научиться делать мебель из поддонов", category: "Обучение и курсы", difficulty: 2, unlockLevel: 4 },
    { id: 728, text: "Освоить 3D-моделирование (основы)", category: "Обучение и курсы", difficulty: 2, unlockLevel: 4 },
    { id: 729, text: "Научиться программировать на Python (основы)", category: "Обучение и курсы", difficulty: 2, unlockLevel: 4 },
    { id: 730, text: "Пройди курс по нейросетям (базовый)", category: "Обучение и курсы", difficulty: 2, unlockLevel: 4 },
    { id: 731, text: "Научиться делать презентации", category: "Навыки и саморазвитие", difficulty: 2, unlockLevel: 4 },
    { id: 732, text: "Освоить базовый английский (100 слов)", category: "Навыки и саморазвитие", difficulty: 2, unlockLevel: 4 },
    { id: 733, text: "Научиться делать умные заметки", category: "Навыки и саморазвитие", difficulty: 2, unlockLevel: 4 },
    { id: 734, text: "Пройти курс ораторского мастерства", category: "Обучение и курсы", difficulty: 2, unlockLevel: 4 },
    { id: 735, text: "Научиться основам фото на зеркалку", category: "Обучение и курсы", difficulty: 2, unlockLevel: 4 },
    { id: 736, text: "Пройти курс каллиграфии", category: "Обучение и курсы", difficulty: 2, unlockLevel: 4 },
    { id: 737, text: "Освоить гончарное дело на круге", category: "Обучение и курсы", difficulty: 2, unlockLevel: 4 },
    { id: 738, text: "Научиться работе в Photoshop", category: "Обучение и курсы", difficulty: 2, unlockLevel: 4 },
    { id: 739, text: "Пройти обучение по оказанию психологической поддержки", category: "Обучение и курсы", difficulty: 2, unlockLevel: 4 },
    { id: 740, text: "Освоить новую цифровую программу", category: "Обучение и курсы", difficulty: 2, unlockLevel: 4 },
    { id: 741, text: "Научиться делать 3D-модели в Blender", category: "Обучение и курсы", difficulty: 2, unlockLevel: 4 },
    { id: 742, text: "Пройти обучение на спасателя МЧС", category: "Обучение и курсы", difficulty: 2, unlockLevel: 4 },
    { id: 743, text: "Освоить 3D-моделирование", category: "Обучение и курсы", difficulty: 2, unlockLevel: 4 },
    { id: 744, text: "Научиться программировать на JavaScript", category: "Обучение и курсы", difficulty: 2, unlockLevel: 4 },
    { id: 745, text: "Пройти курс по машинному обучению", category: "Обучение и курсы", difficulty: 2, unlockLevel: 4 },
    { id: 746, text: "Освоить дизайн интерьеров", category: "Обучение и курсы", difficulty: 2, unlockLevel: 4 },
    { id: 747, text: "Научиться делать сайты на WordPress", category: "Обучение и курсы", difficulty: 2, unlockLevel: 4 },
    { id: 748, text: "Создать свой первый онлайн-курс", category: "Навыки и саморазвитие", difficulty: 2, unlockLevel: 4 },
    { id: 749, text: "Научиться делать бухгалтерию", category: "Навыки и саморазвитие", difficulty: 2, unlockLevel: 4 },
    { id: 750, text: "Освоить основы маркетинга", category: "Навыки и саморазвитие", difficulty: 2, unlockLevel: 4 },
    
    // ============================================================
    // УРОВЕНЬ 5 — ПРОДВИНУТОЕ САМОРАЗВИТИЕ
    // ============================================================
    { id: 751, text: "Получить дополнительное профобразование", category: "Обучение и курсы", difficulty: 3, unlockLevel: 5 },
    { id: 752, text: "Окончить курсы новой специальности", category: "Обучение и курсы", difficulty: 3, unlockLevel: 5 },
    { id: 753, text: "Сдать экзамен по языку на B1", category: "Обучение и курсы", difficulty: 3, unlockLevel: 5 },
    { id: 754, text: "Защитить проект перед экспертами", category: "Обучение и курсы", difficulty: 3, unlockLevel: 5 },
    { id: 755, text: "Пройти большой онлайн-курс 40+ часов", category: "Обучение и курсы", difficulty: 3, unlockLevel: 5 },
    { id: 756, text: "Получить сертификат первой помощи", category: "Обучение и курсы", difficulty: 3, unlockLevel: 5 },
    { id: 757, text: "Пройти курсы выживания 3+ дня", category: "Обучение и курсы", difficulty: 3, unlockLevel: 5 },
    { id: 758, text: "Научиться монтировать в DaVinci", category: "Обучение и курсы", difficulty: 3, unlockLevel: 5 },
    { id: 759, text: "Пройти курс актёрского мастерства", category: "Обучение и курсы", difficulty: 3, unlockLevel: 5 },
    { id: 760, text: "Пройти курсы финансовой грамотности", category: "Обучение и курсы", difficulty: 3, unlockLevel: 5 },
    { id: 761, text: "Пройти курсы ораторского мастерства", category: "Обучение и курсы", difficulty: 3, unlockLevel: 5 },
    { id: 762, text: "Научиться основам фото на зеркалку", category: "Обучение и курсы", difficulty: 3, unlockLevel: 5 },
    { id: 763, text: "Пройти курс каллиграфии", category: "Обучение и курсы", difficulty: 3, unlockLevel: 5 },
    { id: 764, text: "Освоить гончарное дело на круге", category: "Обучение и курсы", difficulty: 3, unlockLevel: 5 },
    { id: 765, text: "Научиться работе в Figma или Photoshop", category: "Обучение и курсы", difficulty: 3, unlockLevel: 5 },
    { id: 766, text: "Пройти курс тайм-менеджмента", category: "Обучение и курсы", difficulty: 3, unlockLevel: 5 },
    { id: 767, text: "Освоить базовую статистику и Excel", category: "Обучение и курсы", difficulty: 3, unlockLevel: 5 },
    { id: 768, text: "Пройти курсы по уходу за пожилыми", category: "Обучение и курсы", difficulty: 3, unlockLevel: 5 },
    { id: 769, text: "Получить права на квадроцикл или снегоход", category: "Обучение и курсы", difficulty: 3, unlockLevel: 5 },
    { id: 770, text: "Пройти обучение по оказанию психологической поддержки", category: "Обучение и курсы", difficulty: 3, unlockLevel: 5 },
    { id: 771, text: "Освоить новую цифровую программу", category: "Обучение и курсы", difficulty: 3, unlockLevel: 5 },
    { id: 772, text: "Пройти курс по экологичному образу жизни", category: "Обучение и курсы", difficulty: 3, unlockLevel: 5 },
    { id: 773, text: "Научиться делать мебель из поддонов", category: "Обучение и курсы", difficulty: 3, unlockLevel: 5 },
    { id: 774, text: "Пройти обучение на спасателя МЧС", category: "Обучение и курсы", difficulty: 3, unlockLevel: 5 },
    { id: 775, text: "Освоить 3D-моделирование", category: "Обучение и курсы", difficulty: 3, unlockLevel: 5 },
    { id: 776, text: "Научиться программировать на Python", category: "Обучение и курсы", difficulty: 3, unlockLevel: 5 },
    { id: 777, text: "Пройди курс по нейросетям", category: "Обучение и курсы", difficulty: 3, unlockLevel: 5 },
    { id: 778, text: "Освоить базовый дизайн интерьеров", category: "Обучение и курсы", difficulty: 3, unlockLevel: 5 },
    { id: 779, text: "Научиться делать сайты на Tilda", category: "Обучение и курсы", difficulty: 3, unlockLevel: 5 },
    { id: 780, text: "Стать наставником для 3 человек", category: "Навыки и саморазвитие", difficulty: 3, unlockLevel: 5 },
    { id: 781, text: "Провести исследование и опубликовать статью", category: "Навыки и саморазвитие", difficulty: 3, unlockLevel: 5 },
    { id: 782, text: "Создать образовательный курс", category: "Обучение и курсы", difficulty: 3, unlockLevel: 5 },
    { id: 783, text: "Открыть свой бизнес", category: "Работа и карьера", difficulty: 3, unlockLevel: 5 },
    { id: 784, text: "Стать экспертом в своей области", category: "Работа и карьера", difficulty: 3, unlockLevel: 5 },
    { id: 785, text: "Сделать мир лучше — реализовать социальный проект", category: "Волонтёрство", difficulty: 3, unlockLevel: 5 },
    { id: 786, text: "Выучить 5 языков народов России", category: "Навыки и саморазвитие", difficulty: 3, unlockLevel: 5 },
    { id: 787, text: "Стать Мастером спорта", category: "Здоровье и тело", difficulty: 3, unlockLevel: 5 },
    { id: 788, text: "Открыть благотворительный фонд", category: "Благотворительность", difficulty: 3, unlockLevel: 5 },
    { id: 789, text: "Создать произведение искусства, которое останется в веках", category: "Искусство", difficulty: 3, unlockLevel: 5 },
    { id: 790, text: "Пройти все 1000 дел этого списка", category: "Челленджи", difficulty: 3, unlockLevel: 5 },
    { id: 791, text: "Воспитать ученика, который превзойдёт учителя", category: "Навыки и саморазвитие", difficulty: 3, unlockLevel: 5 },
    { id: 792, text: "Создать инновационный продукт", category: "Навыки и саморазвитие", difficulty: 3, unlockLevel: 5 },
    { id: 793, text: "Стать лидером в сообществе", category: "Отношения и любовь", difficulty: 3, unlockLevel: 5 },
    { id: 794, text: "Построить дом своими руками", category: "Дом и быт", difficulty: 3, unlockLevel: 5 },
    { id: 795, text: "Запустить свой подкаст", category: "Медиа и информация", difficulty: 3, unlockLevel: 5 },
    { id: 796, text: "Написать мемуары", category: "Творчество", difficulty: 3, unlockLevel: 5 },
    { id: 797, text: "Стать волонтёром международной организации", category: "Волонтёрство", difficulty: 3, unlockLevel: 5 },
    { id: 798, text: "Создать первый в мире рецепт", category: "Кулинария", difficulty: 3, unlockLevel: 5 },
    { id: 799, text: "Организовать фестиваль", category: "Гостеприимство", difficulty: 3, unlockLevel: 5 },
    { id: 800, text: "Стать наставником года", category: "Навыки и саморазвитие", difficulty: 3, unlockLevel: 5 }
];

export default tasks;