// packages/travel.js
// ============================================================
// ПАКЕТ "ПУТЕШЕСТВИЯ" — 100 дел для исследователей
// Уровень открытия: 3
// ============================================================

export const tasks = [
    // ============================================================
    // УРОВЕНЬ 3 — ПРОСТЫЕ ПУТЕШЕСТВИЯ
    // ============================================================
    { id: 151, text: "Посетить город с трудным названием", category: "Путешествия по России", difficulty: 2, unlockLevel: 3 },
    { id: 152, text: "Искупаться в трёх морях России", category: "Путешествия по России", difficulty: 3, unlockLevel: 3 },
    { id: 153, text: "Увидеть закат на Байкале", category: "Путешествия по России", difficulty: 2, unlockLevel: 3 },
    { id: 154, text: "Переночевать в палатке в лесу", category: "Путешествия по России", difficulty: 2, unlockLevel: 3 },
    { id: 155, text: "Увидеть цветение сакуры", category: "Путешествия по России", difficulty: 2, unlockLevel: 3 },
    { id: 156, text: "Посетить столицу республики РФ", category: "Путешествия по России", difficulty: 2, unlockLevel: 3 },
    { id: 157, text: "Увидеть водопад", category: "Путешествия по России", difficulty: 2, unlockLevel: 3 },
    { id: 158, text: "Переночевать в крепости", category: "Путешествия по России", difficulty: 2, unlockLevel: 3 },
    { id: 159, text: "Побывать в настоящей русской бане", category: "Путешествия по России", difficulty: 2, unlockLevel: 3 },
    { id: 160, text: "Увидеть замёрзшее море", category: "Путешествия по России", difficulty: 2, unlockLevel: 3 },
    { id: 161, text: "Проехать на ретро-поезде", category: "Транспорт и дороги", difficulty: 2, unlockLevel: 3 },
    { id: 162, text: "Пересечь регион на междугороднем автобусе", category: "Транспорт и дороги", difficulty: 2, unlockLevel: 3 },
    { id: 163, text: "Проехать за рулём по живописному маршруту", category: "Транспорт и дороги", difficulty: 2, unlockLevel: 3 },
    { id: 164, text: "Попробовать управлять трактором", category: "Транспорт и дороги", difficulty: 2, unlockLevel: 3 },
    { id: 165, text: "Прокатиться на лошади", category: "Транспорт и дороги", difficulty: 2, unlockLevel: 3 },
    { id: 166, text: "Пересечь границу Европы и Азии", category: "Географические точки", difficulty: 2, unlockLevel: 3 },
    { id: 167, text: "Увидеть розовое озеро", category: "Географические точки", difficulty: 2, unlockLevel: 3 },
    { id: 168, text: "Спуститься в пещеру", category: "Географические точки", difficulty: 2, unlockLevel: 3 },
    { id: 169, text: "Посетить Ленские столбы", category: "Географические точки", difficulty: 2, unlockLevel: 3 },
    { id: 170, text: "Подняться на плато", category: "Географические точки", difficulty: 2, unlockLevel: 3 },
    { id: 171, text: "Посетить озеро Светлояр", category: "Географические точки", difficulty: 2, unlockLevel: 3 },
    { id: 172, text: "Найти 10 созвездий без приложений", category: "Астрономия и космос", difficulty: 2, unlockLevel: 3 },
    { id: 173, text: "Увидеть Млечный Путь", category: "Астрономия и космос", difficulty: 2, unlockLevel: 3 },
    { id: 174, text: "Сфотографировать звёздные треки", category: "Астрономия и космос", difficulty: 2, unlockLevel: 3 },
    { id: 175, text: "Понаблюдать за МКС", category: "Астрономия и космос", difficulty: 2, unlockLevel: 3 },
    { id: 176, text: "Посетить планетарий", category: "Астрономия и космос", difficulty: 2, unlockLevel: 3 },
    { id: 177, text: "Найти созвездие Кассиопеи", category: "Астрономия и космос", difficulty: 2, unlockLevel: 3 },
    { id: 178, text: "Побывать на экскурсии в краеведческом музее", category: "Путешествия по России", difficulty: 2, unlockLevel: 3 },
    { id: 179, text: "Посетить старый маяк", category: "Путешествия по России", difficulty: 2, unlockLevel: 3 },
    { id: 180, text: "Погулять по набережной в незнакомом городе", category: "Путешествия по России", difficulty: 2, unlockLevel: 3 },
    { id: 181, text: "Съездить в соседний город на электричке", category: "Путешествия по России", difficulty: 2, unlockLevel: 3 },
    { id: 182, text: "Посетить самый старый храм в регионе", category: "Путешествия по России", difficulty: 2, unlockLevel: 3 },
    { id: 183, text: "Увидеть рассвет в горах", category: "Путешествия по России", difficulty: 2, unlockLevel: 3 },
    { id: 184, text: "Переплыть озеро на лодке", category: "Путешествия по России", difficulty: 2, unlockLevel: 3 },
    { id: 185, text: "Пройти 10 км пешком по неизведанному маршруту", category: "Путешествия по России", difficulty: 2, unlockLevel: 3 },
    { id: 186, text: "Провести день в заповеднике", category: "Путешествия по России", difficulty: 2, unlockLevel: 3 },
    { id: 187, text: "Посетить местный рынок в новом городе", category: "Путешествия по России", difficulty: 2, unlockLevel: 3 },
    { id: 188, text: "Найти самый красивый закат в регионе", category: "Путешествия по России", difficulty: 2, unlockLevel: 3 },
    { id: 189, text: "Покататься на канатной дороге", category: "Путешествия по России", difficulty: 2, unlockLevel: 3 },
    { id: 190, text: "Посетить самый высокий мост в области", category: "Путешествия по России", difficulty: 2, unlockLevel: 3 },
    { id: 191, text: "Увидеть заброшенную усадьбу", category: "Путешествия по России", difficulty: 2, unlockLevel: 3 },
    { id: 192, text: "Проехать по Золотому кольцу", category: "Путешествия по России", difficulty: 3, unlockLevel: 3 },
    { id: 193, text: "Посетить три города за один день", category: "Путешествия по России", difficulty: 2, unlockLevel: 3 },
    { id: 194, text: "Сфотографировать старинную архитектуру", category: "Путешествия по России", difficulty: 2, unlockLevel: 3 },
    { id: 195, text: "Попробовать местную кухню в новом регионе", category: "Путешествия по России", difficulty: 2, unlockLevel: 3 },
    { id: 196, text: "Побывать на озере с чистейшей водой", category: "Путешествия по России", difficulty: 2, unlockLevel: 3 },
    { id: 197, text: "Перейти через горный перевал", category: "Путешествия по России", difficulty: 3, unlockLevel: 3 },
    { id: 198, text: "Посетить самый старый город в области", category: "Путешествия по России", difficulty: 2, unlockLevel: 3 },
    { id: 199, text: "Увидеть цветущие поля", category: "Путешествия по России", difficulty: 2, unlockLevel: 3 },
    { id: 200, text: "Сделать фото с местным жителем в национальном костюме", category: "Путешествия по России", difficulty: 2, unlockLevel: 3 },
    
    // ============================================================
    // УРОВЕНЬ 4 — ПРИКЛЮЧЕНИЯ
    // ============================================================
    { id: 216, text: "Посетить самую южную точку России", category: "Географические точки", difficulty: 3, unlockLevel: 4 },
    { id: 217, text: "Подняться выше 3000 м", category: "Географические точки", difficulty: 3, unlockLevel: 4 },
    { id: 218, text: "Посетить Оймякон зимой при -45°C", category: "Географические точки", difficulty: 3, unlockLevel: 4 },
    { id: 219, text: "Посетить географический центр России", category: "Географические точки", difficulty: 3, unlockLevel: 4 },
    { id: 220, text: "Посетить Куршскую косу", category: "Географические точки", difficulty: 3, unlockLevel: 4 },
    { id: 221, text: "Провести ночь в горах", category: "Путешествия по России", difficulty: 3, unlockLevel: 4 },
    { id: 222, text: "Сплавиться по горной реке", category: "Путешествия по России", difficulty: 3, unlockLevel: 4 },
    { id: 223, text: "Побывать на острове", category: "Путешествия по России", difficulty: 3, unlockLevel: 4 },
    { id: 224, text: "Посетить метеоритный кратер", category: "Путешествия по России", difficulty: 3, unlockLevel: 4 },
    { id: 225, text: "Пройти по экотропе 20+ км", category: "Путешествия по России", difficulty: 3, unlockLevel: 4 },
    { id: 226, text: "Побывать в самой западной точке России", category: "Географические точки", difficulty: 3, unlockLevel: 4 },
    { id: 227, text: "Посетить самую восточную точку России", category: "Географические точки", difficulty: 4, unlockLevel: 4 },
    { id: 228, text: "Увидеть полярное сияние", category: "Путешествия по России", difficulty: 4, unlockLevel: 4 },
    { id: 229, text: "Переночевать в доме на колёсах", category: "Путешествия по России", difficulty: 3, unlockLevel: 4 },
    { id: 230, text: "Проехать по опасному серпантину", category: "Путешествия по России", difficulty: 3, unlockLevel: 4 },
    { id: 231, text: "Посетить регион, где мало говорят по-русски", category: "Путешествия по России", difficulty: 3, unlockLevel: 4 },
    { id: 232, text: "Побывать в настоящей юрте", category: "Путешествия по России", difficulty: 3, unlockLevel: 4 },
    { id: 233, text: "Увидеть живого верблюда в пустыне", category: "Путешествия по России", difficulty: 3, unlockLevel: 4 },
    { id: 234, text: "Сделать круиз по Волге", category: "Путешествия по России", difficulty: 3, unlockLevel: 4 },
    { id: 235, text: "Побывать на фестивале коренных народов", category: "Путешествия по России", difficulty: 3, unlockLevel: 4 },
    { id: 236, text: "Пересечь Северный полярный круг", category: "Географические точки", difficulty: 3, unlockLevel: 4 },
    { id: 237, text: "Увидеть Маньпупунёр", category: "Географические точки", difficulty: 3, unlockLevel: 4 },
    { id: 238, text: "Посетить плато Бермамыт", category: "Географические точки", difficulty: 3, unlockLevel: 4 },
    { id: 239, text: "Проехать по трассе Р-242 (Пермь-Екатеринбург)", category: "Транспорт и дороги", difficulty: 3, unlockLevel: 4 },
    { id: 240, text: "Побывать на мысе Столбчатый", category: "Географические точки", difficulty: 4, unlockLevel: 4 },
    { id: 241, text: "Подняться на плато Путорана", category: "Географические точки", difficulty: 4, unlockLevel: 4 },
    { id: 242, text: "Посетить вулкан Тятя на Курилах", category: "Географические точки", difficulty: 4, unlockLevel: 4 },
    { id: 243, text: "Увидеть северных оленей на Ямале", category: "Путешествия по России", difficulty: 4, unlockLevel: 4 },
    { id: 244, text: "Проехать на поезде по БАМу", category: "Транспорт и дороги", difficulty: 4, unlockLevel: 4 },
    { id: 245, text: "Пролететь на вертолёте над труднодоступным местом", category: "Транспорт и дороги", difficulty: 4, unlockLevel: 4 },
    { id: 246, text: "Посетить все 10 заповедников ЮНЕСКО в России", category: "Путешествия по России", difficulty: 5, unlockLevel: 4 },
    { id: 247, text: "Увидеть миграцию сайгаков в Калмыкии", category: "Путешествия по России", difficulty: 4, unlockLevel: 4 },
    { id: 248, text: "Пройти пешком 100 км по Байкальской тропе", category: "Путешествия по России", difficulty: 4, unlockLevel: 4 },
    { id: 249, text: "Проехать на мотоцикле 500+ км", category: "Транспорт и дороги", difficulty: 3, unlockLevel: 4 },
    { id: 250, text: "Проехать на снегоходе по тайге", category: "Транспорт и дороги", difficulty: 3, unlockLevel: 4 },
    
    // ============================================================
    // УРОВЕНЬ 5 — ЭПИЧЕСКИЕ ПУТЕШЕСТВИЯ
    // ============================================================
    { id: 251, text: "Увидеть северное сияние в Мурманской области", category: "Путешествия по России", difficulty: 4, unlockLevel: 5 },
    { id: 252, text: "Проехать по Транссибирской магистрали", category: "Путешествия по России", difficulty: 4, unlockLevel: 5 },
    { id: 253, text: "Увидеть Кижи, Соловки или Долину гейзеров", category: "Путешествия по России", difficulty: 4, unlockLevel: 5 },
    { id: 254, text: "Подняться на Эльбрус или Белуху", category: "Путешествия по России", difficulty: 5, unlockLevel: 5 },
    { id: 255, text: "Проехать 1000 км на машине за сутки", category: "Транспорт и дороги", difficulty: 3, unlockLevel: 5 },
    { id: 256, text: "Пересечь всю Россию с запада на восток", category: "Путешествия по России", difficulty: 5, unlockLevel: 5 },
    { id: 257, text: "Посетить все 11 часовых поясов России", category: "Путешествия по России", difficulty: 5, unlockLevel: 5 },
    { id: 258, text: "Сплавиться по реке с порогами 4+ категории", category: "Путешествия по России", difficulty: 4, unlockLevel: 5 },
    { id: 259, text: "Провести неделю в полной изоляции в тайге", category: "Путешествия по России", difficulty: 5, unlockLevel: 5 },
    { id: 260, text: "Увидеть Долину смерти на Камчатке", category: "Географические точки", difficulty: 5, unlockLevel: 5 },
    { id: 261, text: "Побывать на мысе Дежнёва", category: "Географические точки", difficulty: 5, unlockLevel: 5 },
    { id: 262, text: "Проехать на оленьей упряжке", category: "Транспорт и дороги", difficulty: 4, unlockLevel: 5 },
    { id: 263, text: "Пересечь Чуйский тракт", category: "Транспорт и дороги", difficulty: 4, unlockLevel: 5 },
    { id: 264, text: "Провести месяц в путешествии по России", category: "Путешествия по России", difficulty: 4, unlockLevel: 5 },
    { id: 265, text: "Посетить все 8 федеральных округов России", category: "Путешествия по России", difficulty: 5, unlockLevel: 5 },
    { id: 266, text: "Увидеть цветущие лотосы", category: "Путешествия по России", difficulty: 3, unlockLevel: 5 },
    { id: 267, text: "Пройти по Большой Байкальской тропе", category: "Путешествия по России", difficulty: 4, unlockLevel: 5 },
    { id: 268, text: "Побывать на крайнем севере", category: "Путешествия по России", difficulty: 5, unlockLevel: 5 },
    { id: 269, text: "Переплыть Байкал", category: "Путешествия по России", difficulty: 5, unlockLevel: 5 },
    { id: 270, text: "Найти «свой» рассвет в России", category: "Путешествия по России", difficulty: 3, unlockLevel: 5 }
];

export default tasks;